### ISSUE TITLE
Is there future for a Non PSR-7 version of Slim?

### ISSUE THREAD

**Issue by r3wt** [slimphp/Slim#1116]
I like it how it is. mostly because i can do this with Slim + Twig:

https://github.com/r3wt/PlebianPHP/blob/master/example.php

**Comment by codeguy** [comment]
It will continue to receive security updates, but no new features. Not _that_ much is changing from an end user point of view. You map routes like you do before. The only difference is the route callbable signature. The new signature is:

```
function ($request, $response, $args) { ... }
```

Where $request is the Request object, $response is the Response object, and $args is an associative array of route pattern segment keys and values extracted from the HTTP request URI. I think this is much nicer than v2. You can continue to `echo` content from your route callable in v3, just like v2.

What exactly do you dislike?

**Comment by r3wt** [comment]
Why change the function signature when you can instead just do `function($args) use($app){}` asi propose in my linked repository. 

Through the method i've demonstrated in the linked repository, one can write PHP without any headaches at all over variable availability to the closure, because you can use `__call()` and `__get()` to access slim/twig/et al. methods from the container class.

**Comment by akrabat** [comment]
The only obvious changes I can see to that code snippet would be:

`$app->args['title'] .= 'Hello World';` => `$app['args']['title'] .= 'Hello World';`

Assuming that `PlebianPHP\SlimTwig` overloads `App::__construct()` and implement `loadTemplate()`.

Have I missed something?

**Comment by r3wt** [comment]
@akrabat literally everything would live as a property of `PlebianPHP\SlimTwig`, eg

`$app->post;`, `$app->files;`, et al.

even request and response would be directly modifiable, with no need to declare then in the route signature

**Comment by codeguy** [comment]
Yeah, this is just not possible given the PSR-7 interfaces. I think you are discrediting value objects without giving them a try. I was skeptical at first, but once I implemented them, I saw how incredibly nice they are to use. You can pass a request and response into other functions or middleware and be safe knowing that your own instances will not be modified somewhere downstream... precisely because they are immutable. Immutability adds a nice safety net and gives the developer more confidence in the state of the objects. I know not everyone will see it this way, but this is where Slim is going.

Slim v2 will always exist here on GitHub. It will continue to merge in security fixes. Its documentation will be made available on its own subdomain before v3 launches. But the v2 branch will not see any additional features.

**Comment by r3wt** [comment]
Well, I'll reserve judgement for the time when 3.0 lands. Thank you for your time.

**Comment by lalop** [comment]
With the Slim 3, I think we can add a middleware just on top of the route handler to wrap the old routes.
Something like :

```
$app->get('/:name', function($name) {
    echo "Hello {$name}";
})->add('Slim2RouteWrapperMiddleware');
```

That can be a good exercise :)

**Comment by lalop** [comment]
Huumm,
In fact we can't do that since the route handler is called by the Route class and not by a middleware.

**Comment by felixfbecker** [comment]
I can see why a Request should be immutable, but the Response? I have to call with*() for every change, and everytime a new object gets created? Especially since the underlying body stream is of course mutable. PSR should have made Request implement the StreamInterface directly, because response headers are just as much part of the stream as anything else, right? Thats how it is in NodeJS.
