### ISSUE TITLE
Setting Content-Type in Response producing json parsing error

### ISSUE THREAD

**Issue by michaelvli** [slimphp/Slim#1201]
When I try to set the content-type of a response header, I'm getting the following error:

```
"SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data "
```

Here's the code:

```
$response["error"] = true;
$response["message"] = "wtf";

respond($response);

function respond($response) {
    $app = \Slim\Slim::getInstance();

    $app->response->headers->set("Content-Type", "application/json");   <=== CAUSING ERROR

    echo json_encode($response);
}
```

Any idea why?  How can I fix this?  I need to send a json response to my AngularJS front-end.  Thanks!

**Comment by JoeBengalen** [comment]
The error is in JavaScript I guess? OR did you make a PHP class named `JSON`.

I do not think the header is the problem. It just tells the requester to interpret the response as json. The error just says you are not returning valid json. Can you post responded string?

EDIT:
On further thought: If you are doing an ajax request from JavaScript without a content type it just act as text, meaning you have to `JSON.parse` the json response string into an object.

When the json content type is defined the ajax call automaticly detects is is json and turns it into an object for you. So I think you are calling `JSON.parse` on an already JavaScript object, instead of a json string.

**Comment by michaelvli** [comment]
D'oh!  Of course, the error is in Javascript!  Thanks, Joe... guess that's what happens when I code late at night.

You're right on - Javascript was having problems with the response (I thought PHP was having problems encoding $response).  But, the root of the problem was from my API - I was sending a json response (content-type in header was set to "application/json") while one of my functions was producing an echo.  Because echos output data in string format, the response that the Javascript front-end was receiving was actually string (from the echo) AND json (from $response), which caused the JSON.parse to break.  So, there were two learnings for me: 

1)  Correctly identify the origin of the error (i.e. client-side or server-side).
2)  Make sure my entire response is actually json (don't mix data types).

Thanks!

**Comment by JoeBengalen** [comment]
Glad to help ;)
