### ISSUE TITLE
Application mode does not correctly sets Slim configuration values

### ISSUE THREAD

**Issue by falmp** [slimphp/Slim#122]
Application mode does not correctly set Slim configuration values, such as log settings, debug settings, etc. This can be reproduced by a clean installation with the following init code:

```
Slim::init(
array(
    'mode' => 'development'
);

Slim::configureMode('development', function () {
    Slim::config(array(
        'log.enable' => true,
        'debug' => true
    );
});
```

This happens because mode determination (settings merge) is done after everything else (in this case, log initialization), so logs settings have no effect.

**Comment by codeguy** [comment]
Thanks for catching this. Will push a fix early this week.

**Comment by codeguy** [comment]
So the potential solution I am considering is moving Logger instantiation into `Slim::run`... this will enable you to configure debugging and logging with `Slim::configureMode` just fine since the logger won't be determined until `Slim::run` is called. However, this means you won't be able to call `Slim_Log::*` outside of route middleware or route callbacks because the logger won't yet exist. Thoughts?

Else, I could move logger instantiation into Slim_Log... when you first call Slim_Log::*, it will check to see if a logger has been set, and if not, it will load the logger determined by the Slim app settings. This will also allow you to use `Slim::configureMode`, with the only exception being you can't call Slim_Log with the expected logger until after you've set the application setting for the given mode.

**Comment by falmp** [comment]
I suppose the first option seems ok, even though you won't be able to call `Slim_Log::*` outside the middlewares or route callbacks. I might be overlooking some situations, but the way I see it all code executed during the request life cycle will be inside these methods.

**Comment by nirandas** [comment]
Hello, 
First of all, I am new to git and github and open source contribution. I find Slim to be really clean and slim. I forked Slim couple of days ago and played around it with it a bit.

As github indicates on this page, I've committed a possible fix to this issue to my fork. It basicly delays the creation of logger, view and session till  configureMode() method has been called if an application mode is provided in Slim::init(). 
If no mode was given in Slim::init(), it works as before, initializing classes during init().

Only change in application behaviur will be that the mode must be specified if config settings are to be changed in configureMode(), even for development mode. A new test for this issue is also included in tests/SlimTest.php.

thanks,

**Comment by codeguy** [comment]
Thanks all for your comments on this thread. @nirandas I'm almost ready to push a large change to the develop branch that already includes a fix for this issue; my change/fix will lazy-load the Logger on-demand using the settings available when the Logger is first requested. I appreciate your contribution and apologize for the unfortunate timing. But I do encourage you to continue to contribute to the framework... currently I am still seeking feedback (but not pull requests just yet) for content negotiation implementation ideas.

**Comment by codeguy** [comment]
A fix for this has just been pushed into the dev branch. Closing this out.
