### ISSUE TITLE
[Develop] Adding Middleware to Route Groups

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim#1265]
Come to find out that the process for adding middleware to route groups is different than adding them to routes.

What I expected:
`$app->group('/', function () { })->add('\Security:check');`

Current
`$app->group('/', \Security:check, function () { });`

Where \Security:check must return a callable which is the middleware wrapped in a function.

So I would suggest 2 things.

1) We change the middleware to be added like route middleware which is a ->add at the end
2) We also add the resolveCallable onto that so that things get resolved properly.

**Comment by lalop** [comment]
:+1:

**Comment by nhymxu** [comment]
:thumbsup:

**Comment by designermonkey** [comment]
I was always a little uncomfortable with how routes and groups were done, so I wrote something to play with that made a new class of `RouteGroup` alongside `Route`.

I'll dig out the code and try to marge it back in to Slim3 (it was a while ago, and many things have changed).

What the code did was made routes and groups essentially the same thing (so things like middleware were handled exactly the same way), but one could have children. It followed the same principal for dispatching, but that part has to be updated due to the PSR-7 work in Slim since I wrote it.

**Comment by dopesong** [comment]
@designermonkey any news about it?

**Comment by designermonkey** [comment]
Sorry guys, responsibilities have taken over again.

**Comment by silentworks** [comment]
@designermonkey is the code available anywhere on Github or can it be available for us to take a look at please?

**Comment by designermonkey** [comment]
Yeah, by all means. This component is never going to get used, so feel free to pull it apart. It was based on Slim anyway.

https://github.com/usebeagle/routes

**Comment by akrabat** [comment]
Implemented.
