### ISSUE TITLE
getBaseUri() returns an empty string instead of a slash

### ISSUE THREAD

**Issue by gouch** [slimphp/Slim#128]
From the tests, I see the expected output from `Slim::request()->getRootUri()` is an empty string (assuming running from root directory), but I would expect the value return to be `'/'`. 

What is the reason for stripping the slash using `rtim`? Is it expected that the closing slash will be added when using the function for output, or is this a bug?

This is an issue since empty hrefs will simply cause the current page to reload. If you view the default Slim 404 page you'll see the "Visit the Home Page" link is broken because of the empty href returned by `getRootUri()`.

**Comment by codeguy** [comment]
This is expected behavior, but perhaps it could be made more intuitive. If you are passing the base URI from your Slim app into templates, you can pass `Slim::request()->getRootUri() . Slim::urlFor('home')`... which will return '/' (I assume) as you would expect. I'll make a note of this... it won't be a high priority until a few other issues are taken care of. Thanks!

**Comment by codeguy** [comment]
Closing this out for now as it's not really an issue but more a suggestion for different behavior. Adding this to the Road Map's list of future considerations so I can keep the Issue Tracker better organized with more immediate issues.
