### ISSUE TITLE
Allow ":" in route URIs

### ISSUE THREAD

**Issue by tobsn** [slimphp/Slim#134]
http://domain.com/:/
results in:
```2011-06-01 17:55:05: (mod_fastcgi.c.2711) FastCGI-stderr: PHP Warning:  array_keys() expects parameter 1 to be array, null given in /www/pages/libs/Slim/Slim.php on line 377
PHP Warning:  in_array() expects parameter 2 to be array, null given in /www/pages/libs/Slim/Slim.php on line 377
PHP Fatal error:  Call to a member function error() on a non-object in /www/pages/libs/Slim/Slim.php on line 501

```
```

**Comment by silentworks** [comment]
You get that because you are in debug mode, I tried it on my production version of a website and all I got is the 404 page I created. I am using Slim develop branch version btw. What version you using?

**Comment by tobsn** [comment]
my version? from like februrary ;)
i need to update but everything else is pretty stable... i can't even remember where i had this issue... :/

wups, accidentally closed it.

**Comment by silentworks** [comment]
When possible can you do a update and update this ticket as to wether this bug is solved or still showing up in your code. Could you close the ticket for now until you test the latest version.

**Comment by silentworks** [comment]
I think you closed the wrong issue. Or maybe I got my threads crossed.

**Comment by codeguy** [comment]
This will be the first item I fix once I am able to start working on Slim again. Been off the grid for a while but should start development again later this week.

**Comment by codeguy** [comment]
@tobsn I've been reading more in the [rfc3986 spec](http://labs.apache.org/webarch/uri/rfc/rfc3986.html#percent-encoding), and the colon character is a reserved character that should only be used unencoded when part of a URI scheme. Otherwise, the spec says it should be percent encoded; this was partially why I chose the colon character to delimit URL parameter placeholders. I'm going to leave these as is for now and follow the spec's recommendations.

EDIT: I am going to resolve the error though to degrade gracefully.

**Comment by codeguy** [comment]
@tobsn Maybe this was resolved on its own in a newer version than when you opened this issue. I'm unable to duplicate the errors you posted above. Can you still duplicate this issue in 1.5.0.3?
