### ISSUE TITLE
POST to URL w/o a trailing slash that has trailing slash in routing is redirected incorrectly

### ISSUE THREAD

**Issue by hulbert** [slimphp/Slim#138]
This may be desired behavior but struck me as wrong. It seems like the POST request should be forwarded.

Here's essentially what I have. I decided I wanted to change all my URLs to trailing slashes, so I changed my routing but not my link at first:

```
$app->post('/contact/', function() use ($app) {
    $response = send_email($app->request());
    switch ($response) {
        case true:
            $app->render('submit_response/success.html');
            break;
        case 'error':
            $app->render('submit_response/error.html');
            break;
        case 'failure':
            $app->render('submit_response/failure.html');
            break;
    }
});


<form method="post" action="/contact">
    <input type="input" value="test" name="somefield">
    <input type="submit">
</form>
```

Submitting the form results in me simply being redirected to /contact/.

**Comment by codeguy** [comment]
Thanks for the detailed report. I won't be able to start up development again until next week (moving and such), but will definitely prioritize this.

**Comment by silentworks** [comment]
This might be a bug but it can be avoided by using $app->urlFor(name)  as the action for the form and set a ->name(name) on the post routing. This will ensure that when you change you route, your action will still point to the right place.

**Comment by codeguy** [comment]
@silentworks Absolutely! A good use for `$app->urlFor(route_name)` as it was intended.

**Comment by codeguy** [comment]
Upon further inspection, this is not really a bug but more an HTTP client implementation issue (e.g. web browsers). An HTTP redirect status in response to a POST request is a source of confusion it seems. POST requests are non-idempotent meaning they should not be arbitrarily repeated at will (unlike GET requests). So the HTTP spec says that if an HTTP client receives a redirect status in response to a POST request, the HTTP client must get confirmation from the end user before performing the redirect. I'd rather not have Slim force the redirect and go against the spec. My suggestion is to update your app's routes rather than rely on auto-redirection. Here are a few links that may be worth reading.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3
http://www.alanflavell.org.uk/www/post-redirect.html
