### ISSUE TITLE
GET, POST, PUT, or DELETE from URL

### ISSUE THREAD

**Issue by ansdma** [slimphp/Slim#140]
Hi,
Can I do any of these operation through the URL without having to use hidden inputs and html, because I'm creating some APIs for an iPhone app and this way may not work for me.

Regards
Alghamdi

**Comment by codeguy** [comment]
Assuming you are submitting HTTP requests from a web browser client... GET and POST will work just fine. You'll have to simulate PUT and DELETE requests as shown in the documentation because browsers do not support those types of HTTP requests. Every framework will have this limitation.

If you are using an HTTP client that supports PUT and DELETE requests (jQuery, cURL, etc.) then Slim should parse those requests correctly without any extra help.

**Comment by ansdma** [comment]
so is this gonna work using jQuery:

```
$.ajax({
    url: '/books/1',
    type: 'DELETE',
    success: function(result) {
    // Do something with the result
    }
});
```

**Comment by codeguy** [comment]
Yes I believe so; I've used a similar script before. If you run into an issue, just let me know.
