### ISSUE TITLE
errorHandling detailed display mode

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#1498]
The detailed error message and stack traces in the errorHandler should not be displayed unless a setting is enabled by the user. This setting should "fail safe" and default to not display this data.

In general, I'd prefer a specific setting rather than a generic "debug" setting that controls lots of different things across the framework.

**Comment by jaapverloop** [comment]
As discussed on IRC, I leave a comment here with the same question.

Is there a specific reason why the error handler does not include the type (class) for xml and json? I expected the same info, no matter the requested format. If it's because of security, we could use this setting you mentioned to hide this kind of information.

**Comment by akrabat** [comment]
No reason at all - it was just missed. Feel free to submit a PR.

**Comment by designermonkey** [comment]
I was talking about this the other day for a project I'm on. We are going for a `?debug` addition to a url to see the output.

**Comment by gabriel403** [comment]
@akrabat can we close this now?
