### ISSUE TITLE
Improve Error and Exception Handling

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#15]
Create a generic SlimException sub-class of Exception. This Exception should be used for:
- Slim::error
- Slim::redirect
- Arbitrary exceptions

The Slim::run method will have a try/catch block which will catch any thrown Exceptions and use the Exception status code to set the HTTP status code, and the Exception message as the response body.

Also, I may change Slim::error to Slim::raise( message, status = 500 ) since this feature may be used for more than just "errors".

**Comment by codeguy** [comment]
This is complete. Slim::error is now deprecated and has been replaced with Slim::raise( $message, $status = 500 ); A try/catch block now surrounds Slim::run and catches SlimExceptions (thrown with Slim::raise), or other non-fatal Exceptions which trigger a 500 response.

**Comment by j4mie** [comment]
Sorry I didn't get chance to look at this last night - your implementation looks great.

I can see a couple of possible issues that still remain. One is the question of what happens to exceptions thrown outside the `run` method. Both the `Router` and the `View` throw `RuntimeException`s which are currently unhandled. Should these also trigger a 500 error? This could be done explicitly (`try`/`catch` block) or we could use `set_exception_handler` to catch everything.

Also, what happens if PHP throws an error rather than an exception? Should these also be handled somehow, with `set_error_handler` perhaps?

**Comment by codeguy** [comment]
Good catch. Looks like I overlooked these last night. I can setup a global exception and error handler which both create and send a stand-alone Response object independent of the actual Slim app.
