### ISSUE TITLE
Gitter.im chatroom

### ISSUE THREAD

**Issue by Lewiscowles1986** [slimphp/Slim#1543]
Just wondering if Slim uses Slack, or could use the gitter.im service?

**Comment by silentworks** [comment]
We have been considering this, but still haven't decided if we will and which service we are likely to use.

**Comment by codeguy** [comment]
What's wrong with IRC?

**Comment by Lewiscowles1986** [comment]
Nothing wrong with IRC per-se, but there can be a certain perception. Also unsure if you use a bot, but if you do probably not a lot of value from Gitter, it basically watches GitHub for issues and PR's and links them, which is nice. Also it's Auth usernames are GitHub usernames

**Comment by mnapoli** [comment]
Hi! I've been using Gitter for quite some time on some of my projects and came to love it. The few times I wanted to go in IRC was to go to the Slim channel and it was always a pain (part because I'm not familiar with it, part because of lacking features).

Here is a list of advantages of Gitter over IRC:
- chat log is public and on a web page (for example see https://gitter.im/PHP-DI/PHP-DI)
- chat log is archived so you can catch up even if you are not connected (though maybe that's possible with IRC?), you can also search messages
- connecting only requires a GitHub account, which is consistent with the repo/issues and most developers have one
- Markdown support, which is pretty nice for formatting text, code, quotations, links, …
- code syntax highlighting (which, for discussing code, is awesome)
- GitHub integration: for example `#123` will be turned into a link #123
- website integration: https://sidecar.gitter.im

And it's compatible with IRC (https://irc.gitter.im) so it doesn't mean you have to drop IRC.

**Comment by samwilson** [comment]
+1 for Gitter.

**Comment by OptimusCrime** [comment]
Slack > Gitter any day of the week.

**Comment by jasteele12** [comment]
+1 for Gitter

Super easy to implement, you don't need to create a "team" like in Slack.  A simple link from the repository is all it takes: [https://gitter.im/slimphp/Slim](https://gitter.im/slimphp/Slim)

I think Slack serves a different audience/purpose...

**Comment by prisis** [comment]
+1 for gitter

**Comment by mnapoli** [comment]
@OptimusCrime I have to disagree as Slack has none of the advantages I listed above except maybe the IRC integration. It is a closed tool that requires creating a Slack-specific account (quite bad for the support of an open source project), is terrible for discussing code (no Markdown support, no code highlighting, no Github integration, …).

If you see advantages to Slack I'd love to see them listed.

**Comment by tuupola** [comment]
-1 for both Gitter and Slack (although I use Slack daily for company I work for). IRC works just fine. Although I must confess I have not tried Gitters IRC gateway.

**Comment by mnapoli** [comment]
@tuupola FYI Gitter is completely compatible with IRC, so it would still work.

**Comment by silentworks** [comment]
I have no objection to Slack or Gitter as I use both for different projects. I also agree with @mnapoli that Gitter would be a better option due to its Github integration and its ease of use over IRC (for some users). 

I think we could use both platforms, but will discuss with the rest of the team and see what everyone else thinks. I guess it will be one more thing for us to manage (keep an eye on) so we have to chat about that aspect of it internally first.

**Comment by akrabat** [comment]
More people are more likely to have Slack open due to using it at work.
