### ISSUE TITLE
ETag caching not working

### ISSUE THREAD

**Issue by alexturpin** [slimphp/Slim#157]
I have a simple Slim app with the following code:

```
<?php
    require 'Slim/Slim.php';

    $app = new Slim();

    $app->get('/', function() use ($app) {
        $app->etag('123');
        echo 'foobar';
    });

    $app->run();
?>
```

This should cache the resource after the first fetch. However, it doesn't. Here are the headers I got from the browser (tried this in both Chrome 12 and FF5):

```
Request URL:http://localhost:8082/test/
Request Method:GET
Status Code:200 OK

Request Headers
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Cookie:PHPSESSID=5bd0c2d02fded05b52c271a604f0822c
Host:localhost:8082
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.122 Safari/534.30

Response Headers
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Type:text/html
Date:Tue, 02 Aug 2011 20:44:19 GMT
ETag:"123"
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=100
Pragma:no-cache
Server:Apache
Set-Cookie:5bd0c2d02fded05b52c271a604f0822c=deleted; expires=Mon, 02-Aug-2010 20:44:18 GMT; path=/
Transfer-Encoding:chunked
Vary:Accept-Encoding
X-Powered-By:PHP/5.3.2-1ubuntu4.9
```

The ETag is set correctly, but there's another header, which I think might be the source of the problem:

```
Expires:Thu, 19 Nov 1981 08:52:00 GMT
```

This would effectively cancel out my ETag. Why is Slim setting that header?

**Comment by codeguy** [comment]
Slim does not set Expires headers... is your web server doing that?

**Comment by hexa2k9** [comment]
I have seen that behaviour as well. In my case it's on nginx 1.0.5, php 5.2.6 via fastcgi on debian 5.0.8 with exactly the same (or almost the same) date somewhen back in Nov 1981.

I personally think it has something to do with the stack you're running. I'm running DokuWiki on that stack which does set Expires Headers that far in History as well. On another version of nginx (same versions of nginx & php) in this case these Headers are not set (or set as expected).

**Comment by codeguy** [comment]
I agree that it is likely the stack... Slim does not explicitly set an Expires header... it only provides methods to set Last-Modified and ETag headers. It's very likely your web server is setting the Expires header due to a default or custom setting.

**Comment by codeguy** [comment]
Closing this out. I'm on IRC in ##slim every day between 9am and 5pm EST if you need further assistance. Happy to help.

**Comment by hexa2k9** [comment]
Just found out since I developed some sort of interest in why this date is set. In php's source `/ext/session/session.c` starting at line 1085 you can find a Line of code whis _does_ set exactly that date: `ADD_HEADER("Expires: Thu, 19 Nov 1981 08:52:00 GMT");` 

See source here: http://svn.php.net/viewvc/php/php-src/trunk/ext/session/session.c?revision=313663&view=markup 

Whyever this has been set, it's the birthday of a person called "Sascha Schumann" who seems to have written that (http://www.phpbuilder.com/lists/php3-list/199911/3159.php).

As a workaround it should still be possible to unset the Header using apache2's module `mod_headers` with a simple 
`Header Unset Expires` 
in your .htaccess. That will make the client use ETag as mechanism used for caching
