### ISSUE TITLE
Normalize Handlers prototypes

### ISSUE THREAD

**Issue by orykami** [slimphp/Slim#1576]
Just some other improvement, why not normalize handlers prototypes : 

``` php
function (ServerRequestInterface $request, ResponseInterface $response, Exception $e) 
```

Exception can be usefull in others Handlers, am i wrong ?

**Comment by piotr-cz** [comment]
At first I thought about that too, but what would we pass as an exception?

For `notFoundHandler` a NotFoundException and for `notAllowedHandler` a NotAllowedException? In both cases it doesn't mean that something bad and unpredictable (exceptional) happened, in contrast to `errorHandler`.

---

There is actually a [NotFoundException](https://github.com/slimphp/Slim/blob/3.0.0-RC1/Slim/Exception/NotFoundException.php) but it's used when trying to access non-existing objects in container

**Comment by Lewiscowles1986** [comment]
Maybe have a clearer laid out `Slim\Exception` namespace then? Two different namespace levels?

`Slim\Exception\Http\NotFoundException` & `Slim\Exception\Container\NotFoundException`

**Comment by piotr-cz** [comment]
I was wrong and things have changed since RC1. Container is now throwing a `ContainerValueNotFoundException` and the `NotFoundException` is available in the App code block calling `notFoundHandler`.

One advantage I see of passing either `NotFoundException` or `MethodNotAllowedException` to appropriate handler is when it would carry on suggested http status code (404, 405).

**Comment by orykami** [comment]
I will try to implement something with it. 
I'll be back ! :coffee:
