### ISSUE TITLE
How to extend \Slim\Container?

### ISSUE THREAD

**Issue by irfanevrens** [slimphp/Slim#1652]
Hello, \Slim\Container is final class. I want to extend it, how can I able to do that?

**Comment by ppetermann** [comment]
final classes can not be extended. 
But you can replace the container used - see documentation
http://www.slimframework.com/docs/concepts/di.html

**Comment by irfanevrens** [comment]
Thanks for reply, I know final classes can not be extended. Why it is final? What is the aim?

**Comment by akrabat** [comment]
It implements an interface. See https://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by irfanevrens** [comment]
I think slim framework should has extendability with all classes. I extended `\Slim\Http\Request` class and customize it with adding some helper function such as `function getReferer()`, `function getServerName()`

**Comment by ppetermann** [comment]
you can easy replace the requests, but you might want to consider another approach:

create a middleware which determines the referer or servername or...
then add it as an attribute to the request (see http://www.php-fig.org/psr/psr-7/)

**Comment by irfanevrens** [comment]
@ppetermann all server variables in `getServerParams()` as array. I created this function my extended Request class.

``` php
private function getServerParam($key)
{
    return isset($this->getServerParams()[$key]) ? $this->getServerParams()[$key] : null;
}
```

But my firstly problem is final keyword on `\Slim\Container`. I think slim framework are not a final product. Again I think `\Slim\Container` class should be extendable.

**Comment by mbretter** [comment]
Let's summarize this:
- Slim\Container is made final due to some design patterns
- I'm putting a lot of stuff (database handles, logger, session manager, cache manager, etc) into the Slim\Container
- Code completion does not work, because the php doc is missing, the solution would be: every time we are using an item from the container putting it into a local var and write the phpdoc for it, produces a lot of unnecessary code and takes time to write
- The other solution is copying the whole Slim\Container, putting this 1:1 into a new Container class and add the phpdoc, everytime Slim is upgraded, the Container has to be manually checked for code changes.

I always enjoyed Slim and I really like the approach of Slim3, but in this case it would be cool choosing the pragmatic way and remove the final keyword from Slim\Container ;)

**Comment by geekish** [comment]
> It implements an interface. See https://ocramius.github.io/blog/when-to-declare-classes-final/

From that article:

> Final classes only work effectively under following assumptions:
> 
> There is an abstraction (interface) that the final class implements
> All of the public API of the final class is part of that interface

Slim\Container implements methods not defined in the implemented interface...

**Comment by silentworks** [comment]
@mbretter and @geekish thanks for all the feedback, we have taken it all into consideration and will be removing final shortly. #1670

**Comment by mbretter** [comment]
great! thanx!
