### ISSUE TITLE
update Request Body won`t update parsedBody

### ISSUE THREAD

**Issue by DavidWiesner** [slimphp/Slim#1803]
Hi,

if I modify the body of a Request the parsedBody won`t be parsed again.
## Steps to reproduce
1. create Request with empty Body
2. set a new body `withBody` with parsable content
3. check result of `getParsedBody` 

``` php
$body = 'foo=bar&abc=123';
$env = \Slim\Http\Environment::mock(
    [
        'REQUEST_METHOD' => 'POST',
        'QUERY_STRING' => 'one=1&two=2&three=3',
        'CONTENT_TYPE' => 'application/x-www-form-urlencoded',
        'CONTENT_LENGTH' => 15,
    ]
);

$slimRequest = \Slim\Http\Request::createFromEnvironment($env);
$bodyStream = $slimRequest->getBody();
$bodyStream->write($body);
$bodyStream->rewind();
$slimRequest = $slimRequest->withBody($bodyStream);

$this->assertSame(15, $slimRequest->getContentLength());
$this->assertSame('application/x-www-form-urlencoded', $slimRequest->getContentType());
$this->assertSame('123', $slimRequest->getParsedBodyParam('abc'));
$this->assertSame('bar', $slimRequest->getParsedBodyParam('foo'));
```
## Expected Result
- `getParsedBodyParams` contains array with keys `abc` and `foo` with values `123` and `bar`
  ## Actaual Result
- `getParsedBodyParams` is an empty array
## Possible Fix
- override `withBody` in `Request` and set `bodyParsed = false` after clone

**Comment by akrabat** [comment]
To avoid any BC break, it looks like the ability to manually force reparsing of the body is the way forward. Something like `$request->reparseBody()`.

**Comment by akrabat** [comment]
@DavidWiesner does #1811 address this issue for your case?

**Comment by DavidWiesner** [comment]
@akrabat that's isn't a good solution! Set `withBody` than schould call `reparseBody` automatically. In  #1804 I also described `getBody()->write()`  should also invalidate the content of `parsedBody` automatically. You can also set a new ContentType with `withHeader` which also should result in re-parsing the body. The easiest solution would be to parse the body every time when `getParsedBody` will called. That would leed to a discussion how often `getParsedBody` will called and how expensive this will be in contrast to more and more guards and checks.

**Comment by akrabat** [comment]
@DavidWiesner I spoke with the authors of PSR-7 and the spec deliberately doesn't link Body with ParsedBody. 

We also can't parse the body every time `getParsedBody()` is called because `withParsedBody()` exists.

i.e according to the spec:

``` php
$data = $request->withParsedBody(['foo'=>'bar'])
                ->withBody('{"one": "two"}')
                ->getParsedBody();
```

results in `$data` being set to `['foo'=>'bar']`

Now , in our case, getParsedBody() can do clever stuff to help you turn structured data in the body into an array within parsed body. This is not part of PSR-7 and is a Slim addition. 

As such, we have now provided a method to allow you to "re-do" this parsing via `reparseBody()` so that you don't have to do it manually.
