### ISSUE TITLE
Mount routes

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#1815]
Is there in Slim a feature that let you mount a given controller to an existing application?
[Silex supports it](http://silex.sensiolabs.org/doc/organizing_controllers.html).

An example of usage would be:

``` php
// define controllers for a forum
$forum = $app['controllers_factory'];
$forum->get('/', function () {
    return 'Forum home page';
});

$app->mount('/forum', $forum);
```

**Comment by akrabat** [comment]
I'm not sure what you mean, but if you have an invokable class registered with the DIC, you can do this:

``` php
$app->get('/forum', 'controllers_factory');
```

In which case, Slim will do this when dispatching:

``` php
$action = $container->get('controllers_factory');
$response = $action($request, $response, $args);
```

**Comment by akrabat** [comment]
I've had a quick read. No Slim doesn't support that in exactly the same way. You have to be explicit with groups:

``` php
$app->group('/blog', function () {
    $this->get('/', 'BlogController:homeAction');
    $this->get('/view', 'BlogController:detailAction');
});
```

This assumes that there is a class called `BlogController` that has two methods, `homeAction` and `detailAction` which both have a signature of `function($request, $response, $args)`.

**Comment by DavidePastore** [comment]
Thanks for the answer. Anyway I think the Silex way would be a nice addition to Slim.

**Comment by OptimusCrime** [comment]
I agree, that SIlex feature is very nice.

**Comment by lalop** [comment]
It seems like the silex way of doing that is more like calling a new Slim app into the controller.
Something like that I think 

```
$forum = new Slim\App();
$forum->get('/', function ($request, $response, $args) {
    $response->write("Forum home page");
    return $response;
});

$app = new Slim\App();
$app->get('/forum', $forum)

$app->run();
```

This code will not work but a simple middleware can do the trick.

**Comment by KuroThing** [comment]
The base concept which i quite like (But i doubt it would actually use) of creating isolated route categories like `$forum` and `$blog` is rather easy to implement. This is a simple implementation that attempts to modify as little as possible.

Step 1) Extend the App class, and add the following code:

``` php
public function mount($group, Router $routes) {
    $app = $this;
    return $this->group($group, function() use($routes, $app) {
        foreach ($routes->getRoutes() as $route) {
            $groupedRoute = $app->map($route->getMethods(), $route->getPattern(), $route->getCallable());

            $name = $route->getName();
            if (!empty($name)) {
                $groupedRoute->setName($name);
            }

            $middlewares = $route->getMiddleware();
            if (count($middlewares) > 0) {
                foreach ($middlewares as $middleware) {
                    $groupedRoute->add($middleware);
                }
            }

            $arguments = $route->getArguments();
            if (count($arguments) > 0) {
                $groupedRoute->setArguments($arguments);
            }

            $buffering = $route->getOutputBuffering();
            if (!empty($buffering)) {
                $route->setOutputBuffering($buffering);
            }
        }
    });
}
```

This adds the mount function to your app object, allowing you to call `$app->mount("/group", $router);` later on. It simply loops over every route in the provided Router, within the prefix provided via the $group parameter. It also tries to bring over all metadata, but i may have missed something and there may be an easier way to do this.

Step 2) Use your new App class rather than Slim. This is as simple as changing the definition of your `$app` (_or whatever you call it!_) variable to point to your new App class!

Step 3) Extending the Router, and adding this function to it

``` php
private $validMethods = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
    "ANY",
];

public function __call($key, $arguments) {

    $method = strtoupper($key);
    if (!in_array($method, $this->validMethods)) {
        return; // ?? Not sure what to do here?
    }

    if ($method == "ANY") {
        $method = array_splice($this->validMethods, 1, 5);
    }

    return call_user_func_array([$this, "map"], array_merge([$method], $arguments));
}
```

Rather than manually mapping all supported HTTP Methods into the Router object like Slim did in the main App object, i opted to use a simple magic method that checks to see if it's a valid method (And converts `Any` into all of them), than calls the `Router->Map();` function with an array of Methods, and the Pattern / Handler.

Step 4) Profit. You are technically complete, create a new instance of your Router (Yes, it has to be new, or you'll have your old routes left in there!), set any routes you want on it, and than load it into the application via `$app->mount();`

@DavidePastore I'm not sure if this will get you want you want, but it should be close!

**Comment by DavidePastore** [comment]
Hi @KuroThing, thanks for the solution. It would be nice if you could create a PR with this code :+1:  @akrabat what do you think about it?

**Comment by KuroThing** [comment]
Ignoring the fact that the provided code doesn't meet PSR-2 Standards that the main Slim project uses and the slight performance overhead of using a magic method rather than actually defining the methods properly, I'm not entirely sure it's worth adding to the main repo.

 I say this, because the main repo alread has the Group method, which is literally all this is doing (Running a group callback behind the scenes), to change the way you define groups. I also don't know if there are any side effects from the Router object having Get, Put, Post, etc methods that may be unintended.

 If the core maintainers have no problems with the duplicating existing functionality, and the Router having the HTTP Method functions, i'll fix the two issues i mentioned in the first paragraph and send a PR.

Edit: I would also need to create unit tests, which would be a new one for me.

**Comment by silentworks** [comment]
I think this has been answered, so closing.
