### ISSUE TITLE
Make it easier to test Slim applications

### ISSUE THREAD

**Issue by maikg** [slimphp/Slim#182]
I might be missing something, but writing tests for Slim applications is not as straightforward as it could be.

Here's what I did for an application I'm currently working on:
- Stub `Slim_Http_Request` to make `getBody()` return a body string of my choosing (there is no way to override the output of PHP's internal `php://input` stream).
- Stub `Slim` to make `request()` return the stub mentioned above.
- Set a large bunch of `$_SERVER` key/value pairs as most of them are unset when working with the application from the command line (I actually stole this trick from some of Slim's own unit tests).
- Write a test harness that hides all this behind a simple API that allows me to perform requests and make assertions on the response.

Is there anything I'm missing and if not, are you open to discussion on how to make testing Slim applications easier?

**Comment by codeguy** [comment]
All good suggestions. After the next release I'll likely take some time to improve Slim's testability.

**Comment by codeguy** [comment]
I pushed version 1.5.2 (beta) to the develop branch yesterday. While there are still a few regressions/bugs that I need to smooth over, it does decouple the environment variables from the `Slim_Http_Request` into the `Slim_Environment` class. The new `Slim_Environment` class has a `mock()` public static method that accepts an associative array of environment variables that _you_ define. This allows you to build mock HTTP requests for your tests. You must provide all required environment variables, though, if you do use the `mock()` method. You can find a list of required environment variables here:

http://www.slimframework.com/documentation/develop#environmentvariables

Leaving this open for comment if you think this idea can be improved.

**Comment by codeguy** [comment]
Closing this out. Here's a status update for each bullet point you mentioned above:

**Stub Slim_Http_Request to make getBody() return a body string of my choosing (there is no way to override the output of PHP's internal php://input stream).**

You can use a mock environment with `Slim_Environment::mock(array('slim.input' => 'your own string'))` to manually specify the HTTP request body.

**Stub Slim to make request() return the stub mentioned above.**

The `Slim_Http_Request` as of 1.6.0 (currently in dev branch) is now an abstraction layer overtop the environment variables. You can override all environment variables using `Slim_Environment::mock(array(...))`. See the development documetation for a list of available/required environment variables. 

http://www.slimframework.com/documentation/develop#environmentvariables

**Set a large bunch of $_SERVER key/value pairs as most of them are unset when working with the application from the command line (I actually stole this trick from some of Slim's own unit tests).**

I'm not entirely sure why this is necessary. I would encourage you to begin using `Slim_Environment::mock()` for future testing. All of Slim's unit tests now do this.

**Write a test harness that hides all this behind a simple API that allows me to perform requests and make assertions on the response.**

This is now possible because of Slim's new Rack architecture. Instead of running the app, you can instead invoke the app's `call()` instance method, passing in the array of Environment settings as its one required argument. This will return an array of (int) status, (Slim_Http_Headers) header, and (Slim_Stream_*|string) body. This makes it super easy to test assertions on the app response to a mock request.

The header implements ArrayAccess and is iterable. If the body is not a string, it will implement a `process()` method that will output/flush data to the client (used for streaming).
