### ISSUE TITLE
Return a popen stream in the response

### ISSUE THREAD

**Issue by Rudloff** [slimphp/Slim#1838]
Hello,

I am trying to return a popen stream like this:

``` php
$stream = \GuzzleHttp\Psr7\stream_for(
    popen(
        'ls', 'r'
    )
);
return $response->withBody($stream);
```

But I see two problems with it:
- For some reason, App::finalize() seems to replace $response->getBody()->stream with an _Unknown resource_.
- `$response->getBody()->getSize()` always returns 0 in this case so App::respond() does not output anything.

**Comment by llvdl** [comment]
I think the underlying issue is that calling [fstat](http://php.net/manual/en/function.fstat.php) on the file pointer returned by [popen](http://php.net/manual/en/function.popen.php) returns a size of `0`.

```
$fh = popen('ls', 'r');
print_r(fstat($fh));  //   prints  [size] => 0
```

This causes `$stream->getSize()` to return `0`. I also tried `\Slim\Http\Stream` instead of `\GuzzleHttp\Psr7\stream_for`, but to no avail.

According to the PHP documentation for `popen`, the file handler should be closed using `pclose` not `fclose`. Both Guzzle and Slim stream implementations use `fclose`. So it seems the Stream class is currently not made for working with `popen` file pointers. 

As a workaround, you could create a class that implement StreamInterface to properly handle the `popen` file pointer, returning `null` when calling `getSize()` and `pclose()` on `close()`.

Since you are using Guzzle, you may want to take this up with the Guzzle developers as well.

**Comment by Rudloff** [comment]
While waiting for the issue to be fixed in \GuzzleHttp\Psr7\Stream or in \Slim\Http\Stream (if it can be fixed), I followed your advice and created a very basic class that extends \GuzzleHttp\Psr7\Stream: https://github.com/Rudloff/psr7-process-stream

**Comment by ghost** [comment]
Size of 0 is expected for pipes. They are unidirectional, you can't do seek, tell or size on them (I mean, you can, but don't expect meaningful results). But fstat works and it tells you that you're dealing with pipe, like so (tested on Debian, OpenBSD and Windows 7):

```
function is_pipe($file) {
    $mode = fstat($file)['mode'];
    return ($mode & 010000) != 0; // This is octal as per headers
}
```

So basically what Slim and Guzzle implementations of StreamInterface should do is:
- switch to `pclose()` instead of `fclose()` when pipe is detected
- return null from getSize() as per PSR7
- throw `\RuntimeException` on `rewind()`
- decide on a consistent behavior for `seek()`, `tell()` and `isSeekable()`

Seek and tell are interesting as you obviously can't seek back (`\RuntimeException`) but does this mean that `isSeekable() == true`? :) Tell is probably implementation dependent as most (not sure if all) OSes have special error code for tell on sockets and pipes.

**Comment by llvdl** [comment]
I have created a pull request that checks for a pipe and if the stream is considered a pipe then:
- `pclose` is used instead of `fclose`
- `getSize()` returns `null`
- `isSeekable()` returns false
- `seek`, `rewind` and `tell` throw a `\RuntimeException`

**Comment by akrabat** [comment]
@Rudloff can you test #1872 and see if that solves your problem?

**Comment by llvdl** [comment]
The current solution assumes that if the stream is a pipe, then the stream is readable pipe. Normally, checking the readability of a stream is determined using `stream_get_meta_data`, but this method does not work for pipes in hhvm.

A pipe can be either readable or writable, depending on the mode given when creating the pipe (this mode cannot be determined in hhvm afterwards).

**Comment by Rudloff** [comment]
@akrabat Yes, it seems to work correctly.
