### ISSUE TITLE
fpassthru usage

### ISSUE THREAD

**Issue by dzsibi** [slimphp/Slim#1841]
Hello,

Is there a particular reason why fpassthru is not used when the response is sent to the client?

**Comment by llvdl** [comment]
Stream are abstracted by the `StreamInterface` interface, which doesn't have a method to read the contents and stream and print it directly. Both `StreamInterface::read()` and `StreamInterface::getContents()` return a string.

Since there is no method to get the underlying stream, `fpassthru` can't be used.
