### ISSUE TITLE
Installation without composer?

### ISSUE THREAD

**Issue by Paratron** [slimphp/Slim#2004]
I know everyone hypes around composer and stuff but Slim is really missing a supid simple download link somewhere to get the framework as a simple ZIP file without forcing people to install other software they don't really care about.

Slim 2 was a simple download and one could start coding. Now Slim 3 makes this suddenly a big hassle.

**Comment by akrabat** [comment]
You need Slim's dependencies for it to work. Composer is the standard in PHP to do this.

See https://akrabat.com/using-composer-with-shared-hosting/ for ideas.

**Comment by Paratron** [comment]
Well, thats sad. I'll continue with Slim 2 then. Thanks for the heads up.

**Comment by phil123456** [comment]
yep, just becos of this, I'll skip that slim thing, it's php, why on earth would it need dependencies

**Comment by akrabat** [comment]
Because software doesn't exist in a vacuum. We don't need to write our own router when there's a really good once already available…

**Comment by Paratron** [comment]
Agreed. Why don't you offer a download package where the 3rd party router is included?

**Comment by akrabat** [comment]
Because modern PHP development is done via Composer in the same way that modern Front End development is done with Bundler. We're not going to create packages with all the other possible libraries thet you may want.

I've already indicated that https://akrabat.com/using-composer-with-shared-hosting/ provides information on how to deploy for a specific individual scenario.

**Comment by Paratron** [comment]
I don't want any other possible libraries - I just want to run slimphp. But don't worry - v2 still works fine and I just used it in another project. I don't care about composer and really don't plan to use it anytime soon :)

**Comment by akrabat** [comment]
As long as you're happy

**Comment by ja-weber** [comment]
On this site you can download all PHP Frameworks without composer. And of course Slim is also available: https://php-download.com/package/slim/slim-skeleton

**Comment by ghost** [comment]
> Because modern PHP development is done via Composer in the same way that modern Front End development is done with Bundler.

This would be your personal opinion, not a fact :/

**Comment by phil123456** [comment]
well call me back when composer installs fine on windows 7 :-)

**Comment by geggleto** [comment]
works just fine on win 7 .... i do it frequently

**Comment by Georangelg** [comment]
Composer sucks...instead in JS npm is an easy-to-use tool for manage dependencies,! should be  exists one similar for php

**Comment by grantalltodavid** [comment]
It's sad the author refuses to provide a standalone download package.  My whole reason for using Slim is it ~~is~~was lightweight.  Forcing me to install composer first wherever I want to use Slim makes it not lightweight anymore.

**Comment by PedroRuiz** [comment]
I code now for a government organization. Therefore, I cannot install anything on my computer. But I can download a zip file.
In this case Slim should give another installation option. For example, to offer the same installation result with the composer as a .zip file.

**Comment by akrabat** [comment]
Composer based projects, including Slim, Laravel, Symfony and Expressive are successfully used in government and other large corporations. If you're in the Node, Go, Java, DotNet or Python worlds, package managers are standard and the accepted way to develop applications. Modern PHP is no different.

**Comment by PedroRuiz** [comment]
Believe me, I can't.

**Comment by adriansuter** [comment]
@PedroRuiz You should convince your organization that it is vital to have a package manager for your work! For example because of security reasons. You want to keep your applications up-to-date, right?

And if your application would need PDF-Support, Spreadsheet-Support, E-Mail-Support? Then you try to install those packages manually, right? A package manager would for example warn you, if there are conflicts between those packages (for example if versions do not work together). Or if a package depends on a package that is already loaded because it is needed by Slim.

It does not make sense for a framework, to provide pre-packaged zip files containing all the dependencies. Because the update cycles of the other packages would not be in the hands of Slim. Therefore, Slim would have to regenerate the zip file every hour or so.

**Comment by carc1n0gen** [comment]
@PedroRuiz You can run composer from a `.phar` file without needing to install it.  No need for escalated privileges or anything `php composer.phar <parameters>`

**Comment by PedroRuiz** [comment]
I can't tell more, but anyway I am grateful for your comments.

**Comment by Paratron** [comment]
The problem is that in nodejs land, npm is already installed when you install node.

Whereas in PHP there are still many servers where you just upload files via FTP and stuff and it just _sucks_ using composer. It always feels like the fifth wheel at the car.

**Comment by Paratron** [comment]
It makes perfectly sense to provide a ZIP package for a PHP framework. Nobody expects it to be up-to-date all the time. Just provide a ZIP package when you release a new version. Worked in the past, will work forever in the future and requires very very small work for the framework maintainer but makes all the people happy that cant/wont use composer for whatever million reasons there are.

**Comment by zelding** [comment]
> [...] It always feels like the fifth wheel at the car.

Do you realize that the 5th wheel is there in case of emergency right ?

It saddens me reading these comments about uploading manually via ftp and downloading zip files and other pre 21st century things.
Maybe if your server is *that* outdated in infrastructure, you shouldn't try to force modern solutions into it. 
Even if you **have to** upload the vendor directory, you can always just compress it, and uncompress it on the server - at the very least that should be available.

If you really need the ZIP package, then do it yourself, and stop bothering everybody else. It is your problem, not everyone elses. 
It is the utmost unreasonable and arrogant to demand others to do it for you. Nobody does that (ZIP packages for PHP dependencies) anymore exactly because composer makes it much more easy and safe to do so.

Start solving your problems, and stop complaining.

**Comment by akrabat** [comment]
I think this discussion has reached its conclusion and is in danger of becoming repetitive and potentially disrespectful to participants.

Slim is now installed via composer since 2015. You are able to use GitHub's release archives if necessary too.
