### ISSUE TITLE
log.path obsolete?

### ISSUE THREAD

**Issue by 84564221** [slimphp/Slim#204]
It seems, that the `log.path` functionality and the ability, to create log-files has been removed in the latest Developer Release (Slim-d886f23).

Why?

**Comment by codeguy** [comment]
Previous versions used a one-size-fits-all approach to logging and assumed that a daily log file was sufficient. The current version writes all logs to STDERR by default, but that is easily changed.

My goal is to make the framework less presumptuous and more flexible. That being said, it is super easy to restore this functionality with a custom log writer:

```
class DailyLogWriter {
    protected $path;

    public function __construct( $path ) {
        $this->path = rtrim($path, '/') . '/';
    }

    public function write( $object ) {
        return file_put_contents($this->path . date('Y-m-d') . '.log', (string)$object . PHP_EOL, FILE_APPEND);
    }
}

$slim = new Slim(array(
    'log.writer' => new DailyLogWriter('../logs')
));
```

I'll likely add some error handling to this custom log writer and merge it into the Slim-Extras repo so that it is readily available. I'll make a note of this change in the docs, too. Leaving this open so anyone else can add his or her ideas.

**Comment by codeguy** [comment]
Closing this out. Custom log writers are the preferred way to perform application logging as of 1.6.0.
