### ISSUE TITLE
Let router resolve `MyController::method` callable with and without container

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2049]
Because the DIC is optional, should we let router continue to resolve `MyController::method` route callables even if no DIC container is specified? Or should the DIC be required to use this callable format?

/cc @akrabat

**Comment by geggleto** [comment]
DIC should be required, imo

**Comment by codeguy** [comment]
Why? You'll still be welcome to provide one, but there won't be one by default. One less dependency. Should also simplify the codebase.

**Comment by kadevland** [comment]
feature propose : add a namespace by default ( by setting)
like App\Controllers

$app->get('\','HomeController::index')  ==> App\Controllers\HomeController

**Comment by akrabat** [comment]
@kadevland You can add `namespace App\Controllers`; to the top of `routes.php` file and you can do that today in Slim 3.

**Comment by geggleto** [comment]
I don't think it really would simplify it at all. Instead of accessing a service from the container we now need our own dependency management solution for Slim's services. The easiest way is singletons, or we end up with our own internal DIC... which raises the question of why bother. 

These are the only 2 solutions that I can come up with, so perhaps there are more options that are better.  

//cc @akrabat @codeguy @silentworks

**Comment by kadevland** [comment]
@akrabat thx for this astuce

**Comment by mathmarques** [comment]
I think we should allow `MyController::method` even without DIC. Otherwise we will be forcing users to add all controllers on the DIC (I'm not saying that this is a bad thing).

**Comment by codeguy** [comment]
After further review, this is actually already in place EXCEPT for one change. We need  to make the `CallableResolver::__construct()` arguments optional.

**Comment by codeguy** [comment]
PR https://github.com/slimphp/Slim/pull/2095

**Comment by codeguy** [comment]
Done
