### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by pheuter** [slimphp/Slim#205]
I'm trying to stream a download being converted on-the-fly via `passthru()` in one of my routes, but instead of streaming the download, server waits until conversion is complete until downloading the whole file. 

Does **Slim Framework** support streaming of piped data as would normally work in PHP via `passthru()` ?

**Comment by codeguy** [comment]
Just thinking out loud here. The process that initiates streaming should be defined within a route callback. The streaming should not be initiated until the Slim app's `run()` method is invoked (the very end of the app lifecycle).

There are two ways I can see this happening. One is a closure, but this is only helpful if you need to maintain a reference to the application state within the callback. Otherwise, we can set the Response body to a hypothetical class instance that is responsible for the streaming. Currently, the Slim app's `run()` method expects the response body to be a string, but we could overload that expectation so that if the Response body is any object with a `process()` method (the method name is only an example), that method will be called rather than doing a simple `echo()` of the Response object's body property.

This way we are sure to send headers first, and then send the Response body (be it a string or an object that handles the Response body).

**Comment by codeguy** [comment]
More thoughts...

We rely on polymorphism... both `Slim_Http_Response` and `Slim_Http_Stream` will implement a `finalize()` method that returns `[status, header, body]`. The two classes are otherwise unrelated.

In `Slim_Http_Stream`, the "body" of the array returned by `finalize()` will be an object instance that implements interface `Slim_Stream_Interface`... we check for this instance in `Slim::run()` where we currently only `echo` the body, and if the instance is found, invoke the instance's `process()` method to initiate streaming rather than echo the response body.

```
Slim_Http_Stream
    protected $streamer;
    public __construct( Slim_Stream $streamer, $options );
    finalize(); //return [status, headers, Slim_Stream body]

Slim_Stream_File implements Slim_Stream_Interface
    public process(); //stream in chunks with fopen/fgets/fclose

Slim_Stream_Data implements Slim_Stream_Interface
    public process(); //echo data

Slim_Stream_Process implements Slim_Stream_Interface
    public process(); //stream in chunks with popen/fgets/pclose
```

**Comment by codeguy** [comment]
Hey everyone,

I've pushed an initial streaming implementation into the **develop** branch. These commits introduce the `streamFile( $path, $options )`, `streamData( $data, $options )`, and `streamProcess( $process, $options )` methods to the Slim class. This implementation is by no means final, but it is a solid foundation from which to start. The method signatures will not change.

I am not entirely sure on the HTTP headers defined in `Slim_Http_Stream::finalize()`. I think they are fine according to the HTTP spec, but some browsers may require some extra legwork to get it working optimally. Feedback is welcome.

You can find more detailed documentation in the respective class files.

All existing unit tests still pass. I have not written tests for these new streaming methods... if anyone wants to work on those that'd be great, otherwise I can add those in next week some time.

## Stream File

```
$app->get('/stream-file', function () use ($app) {
    $app->streamFile('/path/to/file.txt');
});
```

The `streamFile()` method accepts two arguments. The first argument is the path to the file you want to stream to the HTTP client. The second argument is an optional associative array of the streaming settings below. The file will be streamed to the HTTP client until the script time limit is reached or the client severs the connection.

### name

String. The file name sent to the HTTP client (defaults to basename of first argument).

### type

String. The mimetype of the content sent to the HTTP client

### disposition

String. Either "inline" or "attachment" (defaults to "attachment")

### encoding

String. Either "ascii" or "binary" (defaults to "binary")

### allow_cache

Boolean. Dictates which `Cache-Control` and `Pragma` headers are sent to the HTTP client.

### buffer_size

Integer. Bytesize of stream chunks. Default is 8192.

### time_limit

Integer. Time limit of PHP script set when streaming begins. Defaults to 0 (infinite).

## Stream Data

```
$app->get('/stream-data', function () use ($app) {
    $app->streamData('Lorem ipsum dolor sit amet, consectetur adipisicing elit', array(
        'name' => 'lorem.txt',
        'encoding' => 'ascii'
    ));
});
```

The `streamData()` method accepts two arguments. The first argument is the raw data (string) you want to stream to the HTTP client. The second argument is an optional associative array of the streaming settings shown below. The data will be streamed to the HTTP client until the script time limit is reached or the client severs the connection.

### name

String. The file name sent to the HTTP client

### type

String. The mimetype of the content sent to the HTTP client

### disposition

String. Either "inline" or "attachment" (defaults to "attachment")

### encoding

String. Either "ascii" or "binary" (defaults to "binary")

### allow_cache

Boolean. Dictates which `Cache-Control` and `Pragma` headers are sent to the HTTP client.

### buffer_size

Integer. Bytesize of stream chunks. Default is 8192.

### time_limit

Integer. Time limit of PHP script set when streaming begins. Defaults to 0 (infinite).

## Stream Process Output

```
$app->get('/stream-process', function () use ($app) {
    $app->streamProcess('ls -al /usr/local', array(
        'name' => 'file-list.txt',
        'encoding' => 'ascii'
    ));
});
```

The `streamProcess()` method accepts two arguments. The first argument is the process to execute whose output will be streamed to the HTTP client. The second argument is an optional associative array of the streaming settings shown below. The data will be streamed to the HTTP client until the script time limit is reached or the client severs the connection. Unlike `streamFile()` and `streamData()`, this method will stream output line by line rather than in chunks.

### name

String. The file name sent to the HTTP client

### type

String. The mimetype of the content sent to the HTTP client

### disposition

String. Either "inline" or "attachment" (defaults to "attachment")

### encoding

String. Either "ascii" or "binary" (defaults to "binary")

### allow_cache

Boolean. Dictates which `Cache-Control` and `Pragma` headers are sent to the HTTP client.

### time_limit

Integer. Time limit of PHP script set when streaming begins. Defaults to 0 (infinite).

**Comment by guumus** [comment]
OMG. i just realized it now.
Anyway, Since now i'm using Slim Framework. 
And I have a bunch of String names stored in array But when I tried to echo 'em all, I only obtained a partial of the content. Is this related to Slim Buffer or something else?

.

**Comment by codeguy** [comment]
@guumus Not sure how this is related to this particular issue. Can you move your question to http://help.slimframework.com?

**Comment by codeguy** [comment]
Closing. I want to re-think streaming in Slim to make sure it's as good as possible. Will re-visit in the future after 2.0 release.

**Comment by aaronpk** [comment]
Any plans to re-implement streaming? I just found myself in need of it when doing some image processing in the framework.

**Comment by smcphill** [comment]
I know this is an old (and closed) issue, but given we're now at v2.3, is there any chance of an update on streaming?

**Comment by codeguy** [comment]
This is already available in the develop branch and will be merged into the master branch for version 3.0.0 coming soon.

**Comment by kelesi** [comment]
I know this is an old thread. I am stuck on php 5.3 and cannot move to Slim 3.x for at least couple of months (old RHEL server), but I need streaming to output a big csv file without getting out of memory errors. Which commit for 2.6 does include this functionality? Thanks.

**Comment by kavatari** [comment]
> I know this is an old thread. I am stuck on php 5.3 and cannot move to Slim 3.x for at least couple of months (old RHEL server), but I need streaming to output a big csv file without getting out of memory errors. Which commit for 2.6 does include this functionality? Thanks.

Try to search in the repository. Take a look at this commit: https://github.com/slimphp/Slim/commit/4e0dbb0fcfc576f447ebc51ea4cff5894f0171ed
