### ISSUE TITLE
Provide double-pass middleware adapter

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2051]
Related to #2050

**Comment by menismu** [comment]
Reading [PSR-15](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware-meta.md) double-pass is based in a signature including request, response and next callable:

`fn(request, response, next): response`

Current middleware signature in Slim already includes request, response and next callable in the stack as the doc guide shows:

`public function __invoke($request, $response, $next)`

I could be wrong but if I´m understanding well the idea would be to implement single-pass signature and set as default in Slim and keep double-pass as an alternative, is this the case? I´m asking because I´m interested in develop this enhancement and I want to do right.

**Comment by menismu** [comment]
I´ve discovered in #1686 below comment by @akrabat:

Support http-interop (PSR-15). This will change the signature of middleware to:

`function (RequestInterface $request, DelegateInterface $next);`

Hence add() will change to support callables of the format:

`$app->add(function($request, $next) {} ):`

Which means we need to support the current middleware format.
There are two choices:

`$app->add(new DoublePassWrapper(function($request, $response, $next) {} )):`

or:

`$app->addDoublePassMiddleware(function($request,` $response, $next) {} ):`

i.e. we either wrap the middleware before calling add or provide a new method for middleware of this format.

**Comment by akrabat** [comment]
Let's wrap this into #2050
