### ISSUE TITLE
Relocate documentation to main website repository

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#2057]

**Comment by geekish** [comment]
You mean into this repository?

Would you still use Jekyll? Just curious.

**Comment by silentworks** [comment]
Also can we make it all one page again or provide a one page version also?

**Comment by codeguy** [comment]
Not sure why I created this issue. We already did this! Closing.

**Comment by geekish** [comment]
The latest issue (#2130) has me thinking about docs again.

Looking at the 4.0 roadmap (#1686) I think this issue was actually about moving the docs from the website repo into this one, as per your second-to-last bullet point there:

> Move documentation into main repo and publish to website on each new release. That way we can insist on documentation with the PR.

I definitely think this is a good idea:

- If 2.x docs are also moved, all docs will have a unified build, and can be served together; very useful for when 4.x is released or even while it's still in development
- Documentation can be added with PRs here, which should help with "documentation missing" issues
- It will probably be easier to add API docs to the build (#1617) and mayyybe PDF? (#2130 again)

The only problem I can see from this is if docs are moved from their separate homes to a unified one, links will be broken. I have no idea if/how Jekyll/Github Pages handle redirects.
