### ISSUE TITLE
Set view template path at render

### ISSUE THREAD

**Issue by blendsoft** [slimphp/Slim#211]
Hello, 

When I want to set templates.path with config() method:
<?php
require 'Slim/Slim.php';
$app = new Slim();
$app->config(array(
    'debug' => true,
    'templates.path' => 'custom_path',
));

it does not work because templates dir is set by view() method only
which is called from constructor.
so I have to 
add
$app->view($app->config('view'));

But i dont want to change view class so calling config should be enough.

Darek.

**Comment by codeguy** [comment]
Hi Darek. That's a valid concern. I recently changed Slim so that the View was assigned its template path when the Slim app is constructed. However, it is also useful, as you've shown, to ensure the View has the latest template path upon render. I'll push a fix soon so that the View is assigned its template path during Slim instantiation and during render.

**Comment by blendsoft** [comment]
ok, thanks for answer.

**Comment by codeguy** [comment]
I've pushed a fix to the `develop` branch so that the View's template path is set right before render. This fix will be available in the stable 1.6.0 release later this month.
