### ISSUE TITLE
Headers on develop Branch

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#225]
As mentioned on [Discussions](http://help.slimframework.com/discussions/questions/47-develop-lowercase-appended-headers); Headers are being sent lowercase.

May be the way should be to send them 'as-is' (written on source) instead of sending them lowercase. Further replacing those headers (e.g. X-Powered-By) does not work anymore which is the "bigger" problem for me.

**Comment by codeguy** [comment]
Thanks @hexa2k9. To be clear, HTTP headers are case-insensitive. So the only issue here is entirely aesthetic. That being said, I can appreciate the desire to see HTTP headers output exactly as you specify them. Currently, Slim normalizes them into a lower-case canonical form.

So, what I'll have to do is update the `Slim_Http_Headers` class to store a secondary hash of specified header names that maps the canonical form to the original form. The `Slim_Http_Headers` instance will continue to operate in a case insensitive way accepting either lower-case, mixed-case, or upper-case input.

The only change will be "under-the-hood" and will require a tiny bit more overhead to lookup the original form when headers are ultimately flushed to the HTTP client in `Slim::run()`.

**Comment by codeguy** [comment]
@hexa2k9 Pull this commit and let me know how it works for you. Should work great based on my unit tests.

**Comment by hexa2k9** [comment]
@codeguy this works for the lowercase Headers, yes. However it still sends duplicate Headers (e.g. `X-Powered-By` is set by PHP itself and the Slim App I'm running). By design that should not be a major issue, however it could be nice to have a setting/parameter to `$app->response->headers()` to indicate wether the existing one should be replaced or added to it.

**Comment by codeguy** [comment]
@hexa2k9 I do not prevent sending duplicate HTTP headers so that Slim can send multiple `Set-Cookie` headers to the HTTP client (this is in the `Slim::run` method). The original `X-Powered-By` header set by PHP is outside the scope of the Slim app so there's nothing I can do to prevent it from being set. What I can do is to only allow Slim to set duplicate `Set-Cookie` headers but not for any other header. This would solve the problem but remove the ability to use other duplicate headers.

By design, `Slim_Http_Headers` prevents duplicate headers since it acts like a key/value array. However, headers are ultimately flushed in `Slim::run` which does allow duplicate headers. So allowing or disallowing duplicate headers must be determined in `Slim::run`.

I'll think on this for a bit. For now, you can disable the default `X-Powered-By` by adding this line to your PHP.ini file:

```
expose_php = Off
```

**Comment by hexa2k9** [comment]
I'm running php with `expose_php = Off`, however on other servers I'm running the app on these servers don't. I just wanted all app servers to send the same headers.

**Comment by hexa2k9** [comment]
I'm going to use `header_remove('X-Powered-By')` right before sending a new Header for that in the meantime. So don't rush with that ;)

**Comment by codeguy** [comment]
Sounds good. There are arguments to be made either way... the HTTP spec allows duplicate headers, so I do not want to prevent that. However, PHP pollutes the final set of HTTP headers by settings its own without user approval. I'm not sure I want to limit Slim for an inherent PHP shortcoming. I'll think on it. But version 1.6.0 will likely be released based on the current header implementation.
