### ISSUE TITLE
Custom Exception Handler in slim3

### ISSUE THREAD

**Issue by ayushav12** [slimphp/Slim#2256]
I need to build custom exception handler in slim 3. Where should I place the exception handler in the project directory:
In \vendor\slim\Exception (with all the default exception files), or create a new sub-directory inside the root directory??
Anyone please answer ASAP!!

**Comment by pachico** [comment]
You should never write in the `vendor` directory. That folder is entirely managed by composer (it shouldn't even be in your source versioning control system).
Now, if you are familiar with DDD, you might find that `Infrastructure` (or one subfolder, like `Infrastructure/ExceptionHandler/*`) is a suitable path.
Anyhow, as you know, it won't magically be used by placing it there since you have also to register it.

Cheers

**Comment by ayushav12** [comment]
Thanks man for the help!!
