### ISSUE TITLE
Help with www redirect with .htaccess

### ISSUE THREAD

**Issue by joeygallegos** [slimphp/Slim#2317]
Hello! I have a Apache2 running Slim 3 and I have a route setup to be on `https://www.example.com/free-music/` but I want this to redirect to `https://example.com/free-music/` and removing the www but bringing over the same path.

**This is what I have in my .htaccess**

```
<IfModule mod_rewrite.c>
	<IfModule mod_negotiation.c>
		Options -MultiViews -Indexes
	</IfModule>

	RewriteEngine On

	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_URI} (.+)/$
	RewriteRule ^ %1 [L]

	# Move traffic from www to non-www domain (WORKING)
	RewriteCond %{HTTP_HOST} ^www.(([a-z0-9_]+.)?example.com)$ [NC]
	RewriteRule ^(.*)$ http://example.com/$1 [L,R=301]
</IfModule>
```

**What user sees:**
- User lands on **https://www.example.com/free-music/**
- User gets redirected to https://example.com/index.php

I'd like for it to show the same page fired from the router but it's just landing the user on the index.php

Can anybody make any suggestions? I'm really lost.

**Comment by joeygallegos** [comment]
I made some modifications and switched the order of the rewrite conditions and that somehow helped me achieve what I needed (even though I needed to test it in production).

Can anybody maybe just explain why it works now for me? I'm thinking the priority of the conditions is what was throwing the whole request off.

```
<IfModule mod_rewrite.c>
	<IfModule mod_negotiation.c>
		Options -MultiViews -Indexes
	</IfModule>

	RewriteEngine On

	# Move traffic from www to non-www domain
	RewriteCond %{HTTP_HOST} ^www.(([a-z0-9_]+.)?example.com)$ [NC]
	RewriteRule ^(.*)$ http://example.com/$1 [L,R=301]

	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^ index.php [QSA,L]
</IfModule>
```

**Comment by ursoforte** [comment]
Hi @joeygallegos I undertend.
You can see more details in [https://github.com/phanan/htaccess ](https://github.com/phanan/htaccess )
There's a lot of cool stuff.

**Comment by mangopeaches** [comment]
Hey @joeygallegos,

This seems more a pure apache question than a Slim question, but I think I can help clarify the behavior of your rewrite rules.

It looks like your initial set of rules:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L]

# Move traffic from www to non-www domain (WORKING)
RewriteCond %{HTTP_HOST} ^www.(([a-z0-9_]+.)?example.com)$ [NC]
RewriteRule ^(.*)$ http://example.com/$1 [L,R=301]
```
What the first block is doing is essentially checking for an incoming request that's not for a direct file and the request uri ends with a /. If both of those conditions are matched, the page is redirected to that same page, without the trailing slash. So http://www.example.com/free-music/ would be redirected to http://www.example.com/free-music. If your route was always using the trailing slash, then that's probably why this condition was rewriting to index.php instead of the free-music/ route.

There's also something important to note about your rewrite rule. The L in the flags basically tells apache to stop processing rules at this point, so your 301 redirect happens and the following two rules newer are checked.

Moving on to your updated rule set:
```
# Move traffic from www to non-www domain
RewriteCond %{HTTP_HOST} ^www.(([a-z0-9_]+.)?example.com)$ [NC]
RewriteRule ^(.*)$ http://example.com/$1 [L,R=301]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```
Now the first rule set is checking for a request into www.{any-subdomain}example.com and then if that's true it's redirecting tp http://example.com/ and carrying over the request uri and query string. Again, notice the L flag on this rewrite rule, so in the case where this rule is matched apache does a 301 redirect and never scans the next set of rules.

Hopefully that helps explains what was going on with your rewrite rules and it now makes more sense and is less apache magic. Let me know if you have any additional questions.

Best,
Tom

**Comment by odan** [comment]
I would simplify the `.htaccess` file a little bit and move the SSL check and redirect to a middleware.

### Content of `.htaccess`

```htaccess
# Redirect to front controller
RewriteEngine On
# RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

### Middleware

```php
// Redirect HTTP traffic to HTTPS
$app->add(function (Request $request, Response $response, $next) {
    $uri = $request->getUri();
    if($uri->getScheme() !== 'https') {
        // Map http to https
        $httpsUrl = $uri->withScheme('https')->withPort(443)->__toString();

        // Redirect to HTTPS Url
        return $response->withRedirect($httpsUrl);
    }

    return $next($request, $response);
});
```

**Comment by geggleto** [comment]
Server config is outside the scope of our project. If you require config assistance you can try our discourse community or slack.
