### ISSUE TITLE
Problem mocking https requests (wrong port)

### ISSUE THREAD

**Issue by aurmil** [slimphp/Slim#2318]
hello,

I don't know if I do something wrong or docs is wrong or bug

code:

```php
<?php

require 'vendor/autoload.php';

$baseUrl = parse_url('https://example.com');
$envOptions = [
    'REQUEST_METHOD' => 'GET',
    'SCRIPT_NAME' => '/index.php',
    'REQUEST_URI' => '/test',
    'HTTP_HOST' => $baseUrl['host']
];
if ('https' === strtolower($baseUrl['scheme'])) {
    $envOptions['HTTPS'] = 'on';
    // $envOptions['SERVER_PORT'] = '443';
}
$env = Slim\Http\Environment::mock($envOptions);

$app = new Slim\App(['environment' => $env]);

$app->get('/test', function ($request, $response) {
    $baseUrl = $request->getUri()->getBaseUrl();
    return $response->write($baseUrl);
});

$app->run();
```

output: `https://example.com:80`

I have to uncomment line `$envOptions['SERVER_PORT'] = '443';` to get it right: `https://example.com`

[docs](https://www.slimframework.com/docs/cookbook/environment.html):

> SERVER_PORT
The port on the server machine being used by the web server for communication. For default setups, this will be ‘80’; using SSL, for instance, will change this to whatever your defined secure HTTP port is.
HTTPS
Set to a non-empty value if the script was queried through the HTTPS protocol.

**Comment by tflight** [comment]
When the environment is mocked, the `SERVER_PORT` [defaults to 80](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Environment.php#L39) and then array_merge is run with the mocked environment options. So if `SERVER_PORT` is **not** set when mocking the environment, port 80 will always be set regardless of scheme/protocol.

Looks like the documentation is incorrect, or at least misleading. The documentation can be fixed, or we could change the way mock works to check if `HTTPS` is not null and `SERVER_PORT` is null... and if so default to port 443 instead of 80... or something like that.

**Comment by aurmil** [comment]
thanks, did not say more as I did not know if code or docs was to be changed
