### ISSUE TITLE
Whether to start with Slim3 or wait for Slim4

### ISSUE THREAD

**Issue by far-blue** [slimphp/Slim#2320]
Hi guys :)

I'm looking to move some apps over from ZF1 and slim is going to be a good fit for them but I notice that Slim4 has a number of notable breaking changes - differences in how the DIC is used, differences with error handling and 'single pass' PSR standard rather than 'double pass' middleware pipelines.

As I'll be refactoring a few apps that I'd hope will share some middlewares, do you recommend waiting for Slim4 or going with Slim3? I'd prefer not to refactor twice!

Any thoughts?

**Comment by geggleto** [comment]
Slim 3, v4 might be Q1, Q2 of 2018

**Comment by geggleto** [comment]
Also for the most part I do not think the migration path will be all that difficult.

**Comment by far-blue** [comment]
I guess it's the changed fingerprint of the middlewares that concerns me most and the resulting need for middlewares and controllers to create a response object rather than one being passed up the pipeline. I guess it would be possible to do this in Slim3 so as to reduce the problems of migrating to Slim4 - the method calls might change but the architecture will look the same.

**Comment by geggleto** [comment]
We are going to provide adapters the last time I spoke with Rob

**Comment by far-blue** [comment]
Adaptors are great for using old code in new apps but I'd not want to put the effort into migrating lots of code over to a middleware architecture only to then have to refactor it again or forever rely on an adaptor layer.

Unless you were suggesting an adaptor for Slim3 that allows the use of PSR-style middlewares - in which case I could use the adaptor and then ditch it when moving to slim4

**Comment by akrabat** [comment]
The problem is that the new PSR-15 standard isn't agreed yet and the signature has changed at least once between 0.4 and 0.5. You can see this in Expressive 2 where they have to use an adapter to allow for people to target either 0.4 or 0.5…

I'm loathe to support a standard in flux as there's still ongoing discussions about it.

Personally I would go with Slim 3 and migrate when Slim 4 comes out.  The key thing is to ensure that you never use the request or response objects from the container. 

I don't think migrating the middleware will be that hard. To make both middleware and actions easier to migrate, if you a returning your own response rather than the one from `$next`, do not use the passed in`$response`; instead create your own and return it.

**Comment by far-blue** [comment]
thanks for everyone's thoughts :) Most appreciated!
