### ISSUE TITLE
how to use it with the swoole?

### ISSUE THREAD

**Issue by rabbitLove520** [slimphp/Slim#2389]
I have read the source code, the request will get data the the environment:
```
if (!isset($container['environment'])) {
    /**
     * This service MUST return a shared instance
     * of \Slim\Interfaces\Http\EnvironmentInterface.
     *
     * @return EnvironmentInterface
     */
    $container['environment'] = function () {
        return new Environment($_SERVER);
    };
}
```
so, I should add my custom `environment` dependency??

**Comment by pachico** [comment]
Interesting, I made some PoC during the last weeks and I had amazing results.
What you have to do is to pick environment and request data from Swoole Request object and create a Slim request based on that.
During the week I will post an example, but it's really simple.

**Comment by rabbitLove520** [comment]
This is my example:
```
<?php

use Slim\Http\Environment;

define("ROOT", getcwd() . '/..');
define('APP', ROOT . '/app');

require ROOT . '/vendor/autoload.php';
// load functions
require APP . '/functions.php';


$http = new swoole_http_server("0.0.0.0", 8888);

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://0.0.0.0:8888\n";
});

$http->on("request", function ($request, $response) {
    // Instantiate the app
    $settings = require APP . '/config.php';
    $settings['environment'] = function () use($request) {
        $server = [];
        foreach ($request->server as $key => $value) {
            $server[strtoupper($key)] = $value;
        }
        return new Environment($server);
    };
    $app = new \Slim\App($settings);
    // Register routes
    require APP . '/routes.php';

    // Run app
    $slimResponse = $app->run(true);
    $headers = $slimResponse->getHeaders();
    foreach ($headers as $name => $values) {
        $response->header($name, implode(", ", $values));
    }
    $response->header("X-Powered-By", "Salamander");
    $response->end($slimResponse->getBody());
});

$http->start();
```
it works.

**Comment by pachico** [comment]
You're exploiting the potential of an event driven application as Swoole with your approach.
Ideally, what you want to avoid is having to bootstrap your entire application at every request. This means you have to create your app once, then pass it to Swoole's "on("request")" event handler and process that particular request.

I took the liberty of writing a sample which I didn't try so it might have some bugs but it illustrates what I mean.

```php
<?php

require ROOT . '/vendor/autoload.php';

use Slim\Http\Environment;

define("ROOT", getcwd() . '/..');
define('APP', ROOT . '/app');

// load functions
require APP . '/functions.php';

$http = new swoole_http_server("0.0.0.0", 8888);

// Instantiate the app
$settings = require APP . '/config.php';
$settings['environment'] = function () use($request) {
    $server = [];
    foreach ($request->server as $key => $value) {
        $server[strtoupper($key)] = $value;
    }
    return new Environment($server);
};

$app = new \Slim\App($settings);
// Register routes
require APP . '/routes.php';

$http->on("start", function ($server) {
    echo "Swoole http server is started at http://0.0.0.0:8888\n";
});

// You use the already created and bootstrapped app in every request
$http->on("request", function ($request, $response) use ($app) {

    $slimRequest = \Slim\Http\Request::createFromEnvironment(
            new \Slim\Http\Environment([
                'SERVER_PROTOCOL' => 'HTTP/1.1',
                'REQUEST_METHOD' => $request->server['request_method'],
                'REQUEST_URI' => $request->server['request_uri'],
                'SERVER_PORT' => $request->server['server_port'],
                'HTTP_ACCEPT' => $request->header['accept'],
                'HTTP_USER_AGENT' => $request->header['user-agent']
                ])
    );

    $body = new \Slim\Http\Body(fopen('php://temp', 'w'));
    $body->write($request->rawContent());
    $body->rewind();
    $slimRequest = $slimRequest->withBody($body);

    $processedResponse = $app->process($slimRequest, new Slim\Http\Response());

    // Set all the headers you will find in $processedResponse into swoole's $response
    $response->header("foo", "bar");

    // Set the body
    $response->end((string) $processedResponse->getBody());

});

$http->start();
```

Of course, this opens up another way of programming which PHP developers didn't have to suffer from, like:
* If your application registers dependencies or services in you container at each request and not during bootstrap, it will complain;
* you will need to implement policies for opening, reopening and closing database connections (some combinations of DB + DBAL do this automatically);
* If you are using some kind of correlation ids, they will have to be created per request, rather than per bootstrap;
* you will need a supervisor that will monitor if Swoole is running and, if not, start it.
* and many more you will find down the road.

Needless to say, numbers are amazing once you take this in consideration.
I did some tests with one of our micro-services  (simple restful app connected to MariaDB) which had an increment of x10 in throughput.

So, summarizing, all you need is a translator from Swoole's request to Slim(PSR)'s request and then from Slim(PSR)'s response a Swoole's response and flush it. Then, rather than doing `$app->run()` you do `$app->process($slimRequest, new Slim\Http\Response());`. (You might be familiar with this if you are doing functional tests).

Hope this helps.

Cheers

**Comment by geggleto** [comment]
Minor nitpick but in your example coe you don't forward the status code from the processedResponse :)

**Comment by pachico** [comment]
Indeed, nor any headers from the response nor all possible request headers.
I just wanted to illustrate what the overall process was supposed to be. I guess a simple library that will do these transformations could be a good work for a rainy week-end.
Cheers

**Comment by rabbitLove520** [comment]
@pachico 
waiting for your works^_^(maybe your library can be name slim-swoole like others)

**Comment by pachico** [comment]
Challenge accepted

**Comment by pachico** [comment]
@salamander-mh I have started the library. I didn't give it a lot of thought so let me know what you think about it.

https://github.com/pachico/slim-swoole

Of course, contributions are always welcome.

Cheers

**Comment by pachico** [comment]
I think this issue can be closed.
