### ISSUE TITLE
Broken base path detection; remove assumptions/ implement explicit override 

### ISSUE THREAD

**Issue by veeveEdwardHalls** [slimphp/Slim#2452]
When using,
` php -S localhost:8080 bootstrap.php`
None of the requests to http://localhost:8080/resource/ for route /resource will match.

The built in php server sets `$requestScriptName === $requestUri`  so
https://github.com/slimphp/Slim/blob/0803c9ed901db504a42b1f163850b6d5c7c4694a/Slim/Http/Uri.php#L209
will always pass and set the basePath to script name.

then this line, 
https://github.com/slimphp/Slim/blob/0803c9ed901db504a42b1f163850b6d5c7c4694a/Slim/Http/Uri.php#L216
will set `$virtualPath` to '' so it always looks for the default route only.

I guess some assumptions were made for default environment variables. 
Hence, leading to the unexpected when fed the unexpected.

Solution, decouple ourselves from assumptions/expectations: 
1.  Breakout/refactor line 200 to line 216 to a callable that can be a selectable strategy for detection
2. Add an explicit override with a default base path of ( ' ' | '/' ). Bypassing any strategy.

RFC, sample patch to follow

**Comment by akrabat** [comment]
Please provide a simple `bootstrap.php` that shows the issue.

**Comment by Sixtisam** [comment]
I can confirm this issue.

The problem is the following code in `\Slim\Http\Uri` on line 211 - 215:
```php
        if (stripos($requestUri, $requestScriptName) === 0) {
            $basePath = $requestScriptName;
        } elseif ($requestScriptDir !== '/' && stripos($requestUri, $requestScriptDir) === 0) {
            $basePath = $requestScriptDir;
        }
```

As @veeveEdwardHalls already mentioned, when starting the PHP Built-In Server with a router script (see  [https://secure.php.net/manual/en/features.commandline.webserver.php](https://secure.php.net/manual/en/features.commandline.webserver.php)), the two condition will always be `true`. This causes, that Slim assumes the entire Path as the basePath. As a consequence, the route `/` will always match, for any path.

I dont know really how to fix this properly.
Currently, I'm fixing it by placing
```php
if(php_sapi_name() == 'cli-server') {
    $_SERVER['SCRIPT_NAME'] = '/bootstrap.php';
}
```

on top of bootstrap.php.

**Comment by l0gicgate** [comment]
We should just refactor the entire `Uri` component based on [Nyholm/psr7/Uri](https://github.com/Nyholm/psr7/blob/master/src/Uri.php)

**Comment by akrabat** [comment]
I use `php -S 0.0.0.0:8888 -t public/` with Slim 3 apps with no problem.

I don't mind changing `Uri` so that `php -S localhost:8080 bootstrap.php` also works as long as there's no BC breaks.

**Comment by l0gicgate** [comment]
This is essentially how Slim-Skeleton circumvents the issue:
https://github.com/slimphp/Slim-Skeleton/blob/master/public/index.php#L2-L10

**At the very top of index.php**
```php
<?php
if (PHP_SAPI == 'cli-server') {
    // To help the built-in PHP dev server, check if the request was actually for
    // something which should probably be served as a static file
    $url  = parse_url($_SERVER['REQUEST_URI']);
    $file = __DIR__ . $url['path'];
    if (is_file($file)) {
        return false;
    }
}
```

I don't know if we can actually PR that on `Uri` and add this piece of logic to make sure that's the default behavior. @veeveEdwardHalls or @Sixtisam would one of you guys like to PR this?

I'm going to flag the issue as stale/wontfix otherwise since we're so deep in the `3.x` release cycle.
