### ISSUE TITLE
simple string json not parsed as getParsedBody

### ISSUE THREAD

**Issue by mhf-ir** [slimphp/Slim#2453]
Null request:
```bash
curl -X POST "http://localhost/api/echo" -H "accept: application/json" -H "Content-Type: application/json" -d '"string"'
```
```php
var_dump($request->getParsedBody()); // null
```

Parsed request
```bash
curl -X POST "http://localhost/api/echo" -H "accept: application/json" -H "Content-Type: application/json" -d '{"a": 1}'
```
```php
var_dump($request->getParsedBody()); 
/*
array(1) {
  ["a"]=>
  int(1)
}
*/
```

**Comment by kip-13** [comment]
Your first request is not a valid JSON and when Slim try to parse it, it doesn't recognized and return null.

https://github.com/slimphp/Slim/blob/0803c9ed901db504a42b1f163850b6d5c7c4694a/Slim/Http/Request.php#L206-L212

**Comment by chris48s** [comment]
Its an edge case, but [RFC 7159](http://www.faqs.org/rfcs/rfc7159.html) defines a string as valid json, and `json_decode()` will parse it:

```
$ php -a
Interactive mode enabled

php > var_dump(json_decode('"foo"'));
php shell code:1:
string(3) "foo"
```

This behaviour in Slim does appear to be a conscious design decision though. See https://github.com/slimphp/Slim/commit/dc5092cfbc7e7f332c541d6603746ab2e3e0d655

**Comment by akrabat** [comment]
Given that getParsedBody() returns an associative array, what would be returned for a JSON body of `"string"` ?

**Comment by chris48s** [comment]
Oh I see. Looks like PSR-7 is a rock and RFC7159 is a hard place on this one ;)

**Comment by kip-13** [comment]
@chris48s see this from [RFC 7159](http://www.faqs.org/rfcs/rfc7159.html)

> 13.  Examples
> 
>    This is a JSON object:
> 
>       {
>         "Image": {
>             "Width":  800,
>             "Height": 600,
>             "Title":  "View from 15th Floor",
>             "Thumbnail": {
>                 "Url":    "http://www.example.com/image/481989943",
>                 "Height": 125,
>                 "Width":  100
>             },
>             "Animated" : false,
>             "IDs": [116, 943, 234, 38793]
>           }
>       }
> 
>    Its Image member is an object whose Thumbnail member is an object and
>    whose IDs member is an array of numbers.
> 
>    This is a JSON array containing two objects:
> 
>       [
>         {
>            "precision": "zip",
>            "Latitude":  37.7668,
>            "Longitude": -122.3959,
>            "Address":   "",
>            "City":      "SAN FRANCISCO",
>            "State":     "CA",
>            "Zip":       "94107",
>            "Country":   "US"
>         },
>         {
>            "precision": "zip",
>            "Latitude":  37.371991,
>            "Longitude": -122.026020,
>            "Address":   "",
>            "City":      "SUNNYVALE",
>            "State":     "CA",
>            "Zip":       "94085",
>            "Country":   "US"
>         }
>       ]
> 
>    Here are three small JSON texts containing only values:
> 
>    "Hello world!"
> 
>    42
> 
>    true

You are right, is a valid syntax that `json_encode()` must recognize and not show any error but is not a JSON text that represent a **JSON object** or **JSON array** is only a **single value**(primitive type).

How do you can parse an single value that isn't an structure ? But if you read again:

> JavaScript Object Notation (JSON) is a text format for the serialization of structured data.

I think you can only get a structure (as @akrabat said "getParsedBody () returns an associative array") from another that can be analyzed like that...

**Comment by akrabat** [comment]
Fortunately, you can always `json_decode($request->getBody())` yourself.

**Comment by designermonkey** [comment]
I'm closing this as there is nothing we could do in this case. If there is any more info to add, please do and it can be reopened.

**Comment by jjsaunier** [comment]
> Your first request is not a valid JSON and when Slim try to parse it, it doesn't recognized and return null

It's not better to throw an exception rather than fail silently here ? In that way it's can be catch from errorHandler to transform it into 400 bad request instead. And we need to explicitly catch the error to handle it from controller rather than the opposite logic (checking each time if it's not null)

**Comment by designermonkey** [comment]
The return of `null` is from `json_decode` not Slim. Personally, I would say that this is acceptable for a micro-framework.

Any extra error handling, exception throwing and/or better json decoding using a serializer for example, should all be done by extending the framework with middleware, parsers and the like.

There's a reason we call it a micro-framework instead of doing all this for a developer.

**Comment by akrabat** [comment]
> It's not better to throw an exception rather than fail silently here ? In that way it's can be catch from errorHandler to transform it into 400 bad request instead. And we need to explicitly catch the error to handle it from controller rather than the opposite logic (checking each time if it's not null)


The [spec](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php#L152-L167) for getParsedBody() doesn't throw an Exception.

**Comment by jjsaunier** [comment]
@designermonkey yes it's acceptable at this time, my point it's that could be improved for furtur version. In php 7.3 json decode can throw exception rather than failing silently, failing silently is not a good practice and php core fixed it. But again, I understand the point that slim should not do too much. Reconsider this later to follow next json_decode implemention from core. 

@akrabat indeed, what's your point about that, IMO it should throw an `\InvalidArgumentException` like  `withParsedBody` - I know it's not slimphp scope - I have open discussion to have more detail and challenge the current signature against that case - https://github.com/php-fig/fig-standards/pull/1071 May be I miss something

**Comment by jjsaunier** [comment]
@akrabat didn't see it before, but you already broke it : https://github.com/slimphp/Slim/blob/1ca78596de8f1b0e2389b812a6ce64d1ccd9e49f/Slim/Http/Request.php#L1044

**Comment by akrabat** [comment]
Yeah, that handles the situation when someone registers a non-conforming media parser to the Request object. The built-in parsers will never trigger that exception.

**Comment by jjsaunier** [comment]
Ok, let's think differently, if we move decoding part outside of request object scope, and fill it via `withParsedBody` instead ? then `getParsedBody` becomes anemic, and decoder are free to throw exception on error. We need to move the decoding logic when request is created. 

In that way, we fixed current exception and the bad content issuen, What do you think ?

**Comment by akrabat** [comment]
Happy to look at that in [Slim-Http](https://github.com/slimphp/Slim-Http). 

The only potential problem I can see is that we may end up doing parsing work that isn't needed if we pre-parse and then the user doesn't call `getParsedBody()` which would slow down the request.

**Comment by jjsaunier** [comment]
Yep, that's why closure are not a bad choice in `getParsedBody`. Another line of throught, if we already broke the psr7 interface, we could do it twice for a good reason (yes there is no good reason, ssht :stuck_out_tongue:) My point is if we throw an exception, does it solves more problem than it creates, or as popular OSS project should we strictly follow PSR-7 or could we make a little exception do handle it in best manner for us.

**Comment by jjsaunier** [comment]
> The only potential problem I can see is that we may end up doing parsing work that isn't needed if we pre-parse and then the user doesn't call getParsedBody() which would slow down the request.

@akrabat the response of @weierophinney in https://github.com/php-fig/fig-standards/pull/1071#issuecomment-419982991 could be a good solution to that problem, plus with PSR15 support in v4 it's match
