### ISSUE TITLE
Slim Request converting  blank object to array

### ISSUE THREAD

**Issue by sks40gb** [slimphp/Slim#2498]
JSON String is being passed which has the some object which has the properties however there could be some which doesn't have any property.  When object is being retrieved from $request->getParams(), its giving the empty array instead of stdClass type.

Input Json Ex 
-----------------------
```
{
   "name ": "John",
    "address ": {  }      //this is getting converted as array(0)
}
```
I had seen the code of Slim Request which has the following code which is causing the issue. I am wondering if we have anyway to override this.

`$result = json_decode($input, true);`

**Comment by RyanNerd** [comment]
Look here https://www.slimframework.com/docs/v3/objects/request.html at the section that describes Media Type Parsers.

It's not clear in the docs if you can override the existing `application/json` handler (below). I've not tried it but it appears that as long as you register 'application/json' _after_ the Request object has been instantiated it will use your function instead of the built-in one:

`Slim/Http/Request.php`

```php
        $this->registerMediaTypeParser('application/json', function ($input) {
            $result = json_decode($input, true);
            if (!is_array($result)) {
                return null;
            }
            return $result;
        });
```

**Comment by akrabat** [comment]
As @RyanNerd says, register your own media type parser for `application/json` into the request object in an early middleware and you should be fine.
