### ISSUE TITLE
sentry issue

### ISSUE THREAD

**Issue by mhndev** [slimphp/Slim#2527]
Hi,
I don't know it is the right place to ask this question or not, but I wanted to integrate sentry as my slim project error tracker.
I asked a question in stackoverflow, but I got no answer.
here is my question.
https://stackoverflow.com/questions/53025413/i-cant-add-sentry-to-php-slim

**Comment by jjsaunier** [comment]
Hey, 

You should declare it very earlier, before filling the container. 

```php
$app = new App($settings);

/** @var Container $container */
$container = $app->getContainer();

if ('dev' !== $container->get('settings')['app']['env']) {
    $sentry = new \Raven_Client('xxxx', [
        'environment' => $container->get('settings')['app']['env'],
        'release'     => $container->get('settings')['app']['version'],
        'site'        => $container->get('settings')['app']['domain'],
        'sample_rate' => 0.5,
    ]);

    $sentry->tags_context([
        'php_version' => PHP_VERSION,
    ]);

    $sentry->install();
} else {
    $sentry = null;
}

$container['sentry'] = function (ContainerInterface $c) use ($sentry): ?\Raven_Client {
    return $sentry;
};

$container['logger'] = function ($c) {
    $settings = $c->get('settings')['logger'];
    $logger = new Monolog\Logger($settings['name']);
    $logger->pushProcessor(new Monolog\Processor\UidProcessor());
    $logger->pushHandler(new Monolog\Handler\StreamHandler($settings['path'], $settings['level']));

    $handler = new Monolog\Handler\RavenHandler($c->get('sentry'));
    $handler->setFormatter(new Monolog\Formatter\LineFormatter("%message% %context% %extra%\n"));

    $logger->pushHandler($handler);

    return $logger;
};
 // container declarations ... 

```

Arrange the code as your need ofc, it's from one of my apps. 

In your case It's not working because you declare it inside a closure which may not be executed until a service require it to start. e.g : `$container->get('logger');` will resolve the closure and raven will be instanciated.

By declaring it much earlier as you can, sentry is already instanciated and wired to php and can track all errors, without side effect of DI. In your script, sentry is started only if the DI (you assume the DI can't bug at runtime, which is wrong) do not throw an error, it's not perfect for monitoring purpose.

You can also start it before calling `$app = new App($settings);` in my case, it's trivial code that can't "bug", depends of what you do.

Hope it's solve your problem

**Comment by mhndev** [comment]
thanks for your help,
with this line of code :
`
set_error_handler(function ($errno, $errstr, $errfile, $errline ,array $errcontex) {
    throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
});
`
![untitled](https://user-images.githubusercontent.com/5164182/47612592-566f9100-da93-11e8-8080-67a597eec21c.png)

at the very beginning of my code, now it catches all errors and exceptions.
but my next issue is in my sentry dashboard, It doesn't group same exceptions as one record.

**Comment by odan** [comment]
Hi, try this:

[Logging minor errors (like notice and warnings) with Monolog in Slim 3](https://odan.github.io/2018/10/28/logging-minor-errors-like-notice-and-warnings-with-monolog-in-slim-3.html)

**Comment by l0gicgate** [comment]
Closing this issue as there has not been activity since end of October. Please join our [Slack Channel](https://slimphp.slack.com) for further assistance.
