### ISSUE TITLE
Command for preparing route cache file

### ISSUE THREAD

**Issue by garipovazamat** [slimphp/Slim#2568]
Hello guys. I didn't find command for preparing cache file for routes. I have to create custom script which will generate route file before publishing my project to production.
This feature will be very useful, I think.

**Comment by l0gicgate** [comment]
Here's a simple script to create a route cache file in **Slim 3**:
```php
#!/usr/local/bin/php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$app = new App();
$container = $app->getContainer();
$router = $container->get('router');

$routeCollector = new \FastRoute\RouteCollector(
    new \FastRoute\RouteParser\Std(),
    new \FastRoute\DataGenerator\GroupCountBased()
);

foreach ($router->getRoutes() as $route) {
    $method = $route->getMethod();
    $pattern = $route->getPattern();
    $handler = $route->getIdentifier();
    $routeCollector->addRoute($method, $pattern, $handler);
}

$outputFile = __DIR__ . '/route.cache';
file_put_contents($outputFile, '<?php return '  . var_export($rc->getData(), true) . ';');
```

@akrabat would you like to create some sort of helper method to dump out a compiled router cache file? I don't think this should go into core.

**Comment by akrabat** [comment]
I suspect that this should be in the documentation if it isn't already.

**Comment by l0gicgate** [comment]
@akrabat the only thing I could find about `routerCacheFile` is [here in the docs](http://www.slimframework.com/docs/v3/objects/application.html#slim-default-settings) all the way at the bottom.

It describes the setting but it doesn't define on how to generate the cache file. Would you like me to migrate this issue to the Slim-Website repo?

**Comment by garipovazamat** [comment]
> I don't think this should go into core.

Why?

**Comment by garipovazamat** [comment]
In Slim/Router.php class, in setCacheFile method checked is_writable
```
if ($cacheFile !== false && !is_writable(dirname($cacheFile))) {
     throw new RuntimeException('Router cacheFile directory must be writable');  
}
```
I have already file, where I will write, and it writible, but not all directory. So, I had to override this method.
May be checking directory if only file doesn't exist is better way?

**Comment by l0gicgate** [comment]
> Why?

It is not the App's responsibility to generate the router's cache file. A utility package should be built for that.

> In Slim/Router.php class, in setCacheFile method checked is_writable

We need write permissions on the directory because if the `routerCacheFile` is set but doesn't exist `FastRoute` [detects if file exists](https://github.com/nikic/FastRoute/blob/master/src/functions.php#L50) and if it doesn't it [will create it/keep it up to date](https://github.com/nikic/FastRoute/blob/master/src/functions.php#L65-L70) when instantiating the `cachedDispatcher`.

@akrabat we could change that logic up a bit actually. We need to check if the file exists, if it exists check if it's writable. If it doesn't exist, we need to check if the directory is writable. 

On a side note, looking at the behavior from FastRoute, it will automatically generate the cache file if the file is set but does not exist. So the need for a method to generate the file is useless. We just need to document the behavior better.

**Comment by akrabat** [comment]
> @akrabat we could change that logic up a bit actually. We need to check if the file exists, if it exists check if it's writable. If it doesn't exist, we need to check if the directory is writable.

Sounds reasonable to me.

**Comment by akrabat** [comment]
> On a side note, looking at the behavior from FastRoute, it will automatically generate the cache file We just need to document the behavior better.

Agreed.

**Comment by l0gicgate** [comment]
Sounds good, I will PR that for **3.x** and then **4.x** a bit later. Will also update docs on my end

**Comment by garipovazamat** [comment]
If I want to use Router only for reading cache file, without rewriting it, and I dont have permission to write it then checking is_writable won't allow me to use this file. May be is better to check is_writable when we want to write in file?

**Comment by l0gicgate** [comment]
@garipovazamat the issue being fixed by my PR. If the file already exists, it performs an is_writable check on the file, if it doesn’t exist it does a check on the directory instead because FastRoute will try and create the file if it doesn’t exist so it needs write permissions. 

As I pointed in the PR, in order for FastRoute to generate the cache file without having to write any code, you simply need to point it to a file that doesn’t exist in a directory where you have write permissions.

So I suggest that you nest your cache file in a directory that you own/can write to if you don’t have write permissions on your root directory for whatever reason.

**Comment by l0gicgate** [comment]
> If I want to use Router only for reading cache file, without rewriting it, and I dont have permission to write it

FastRoute always tries to overwrite the file when you instantiate `FastRoute\cachedDispatcher()` this is why we need write permissions on the existing file or directory. 

https://github.com/nikic/FastRoute/blob/master/src/functions.php#L65-L70

**Comment by garipovazamat** [comment]
> FastRoute always tries to overwrite the file when you instantiate `FastRoute\cachedDispatcher()`

In FastRoute checked file_exists and if it exists will `return new $options['dispatcher']($dispatchData);` without rewriting file.
https://github.com/nikic/FastRoute/blob/66cc306f8360f4d9a7a5b9ad8b3c9a85d12b6e5c/src/functions.php#L55

**Comment by l0gicgate** [comment]
> In FastRoute checked file_exists and if it exists will `return new $options['dispatcher']($dispatchData);`

You are correct. I missed that bit! I will change one of the two checks to is_readable instead of is_writable if the file exists! 

Thank you for pointing that out

**Comment by ilyachase** [comment]
The idea is that *routes* are *static* entity and they are hardcoded in app source code. Therefore, cache file for routes *should not change* in a runtime. So we wanted to add another step in our deploy pipeline to create cache file *once* for current release package, but for some reason framework forced this file to be writable (and even its base directory).

Glad you guys figured it out, thanks!
