### ISSUE TITLE
Inner routes

### ISSUE THREAD

**Issue by AlexandraK** [slimphp/Slim#259]
Let's say you have a set of routes like these:

```
  /site.com/admin/welcome
  /site.com/admin/settings
  /site.com/admin/pages(/:page)
  /site.com/admin/users(/:user)
  /site.com/admin/bla/bla
  ...
```

If you have like 100 of these routes, the matching will be quite slow, so I was thinking we could map a single route like this:

```
`/site.com/admin/*`
```

and if this matches, a new match is fired for the inner routes, and maybe the extra path segments are provided as argument in the route callback

What do you think?

**Comment by xjia1** [comment]
I think the real problem is that you have to match routes one by one against a given path. Even though you have that inner routes, you still have to go through these routes which might be slow. So I think a more practical and general solution to this issue is to construct a DFA for routing when you `run` the `app`. However such kind of things seems suitable for C extensions rather than PHP itself.

**Comment by StJudeWasHere** [comment]
@AlexandraK you could organize your routes code in different files and use the slim.before hook to include the needed one depending on the requested uri.

Something like this:

```
$app->hook('slim.before', function() use ($app) {
    if(preg_match('/^\/admin/', $app->request()->getResourceUri())) {
        include 'AdminRoutes.php';
    }
    else {
        include 'RegularRoutes.php';
    }
});
```

However, as @oipn4e2 pointed out you still have to go through all loaded routes.

**Comment by AlexandraK** [comment]
I did a test by mapping 1000 routes and the performance hit is not the big, even if you iterate trough all of them on each page load (+ ~0.1s), so I guess it's ok to map many routes :P

**Comment by xjia1** [comment]
Good news. So you may close this issue now. :-)
