### ISSUE TITLE
How do you change the invocation strategy for a specific route?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2597]
Should it be possible to change the invocation strategy for a specific route? If so, how would we do so?

**Comment by l0gicgate** [comment]
Do you mean after it's been added? If so, why? 

You can define the invocation strategy when you instantiate `Route`. Right now there is no setter on `Route` for that property though, in order to do that you'd need to set the `InvocationStrategy` on `Router`, then add your route. 

I think it might be something that we need to add into the router proxy methods from `App`, when you add a route you could specify the invocation strategy like so:
```php
$app = new App(...);
$app->get('/', function () {...}, <Your Optional Invocation Strategy>)
```

I don't think we need to provide the option of changing the invocation strategy after the `Route` object has been instantiated though.
