### ISSUE TITLE
Middleware stack improvements?

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim#2613]
https://twitter.com/auroraeosrose/status/1108344489830203392:

> Really hate that in slimphp I can't 
> 1. Get the count of middleware attached 
> 2. Manipulate the stack or pre/post hook
> 3. See if any middleware is attached at all 
> 4. Replace the stack implementation with my own that does all these things

Can we address any of these items for Slim 4?

**Comment by auroraeosrose** [comment]
Oh look you're making issues for me :)

Having a way to compose in a middleware container if desired would probably solve the majority of "crazy edge case" problems while allowing for backwards compatible use out of box - this would allow issues related to "I want my middleware to be some kind of fancy stack or queue" to be punted onto the user without having to hack the core code.

I think just incrementing a registered middleware count would help for the "is my stuff registered?" - because of the nested callable method of using the tip in the default implementation it's very hard to introspect any of the middleware data, which leads to testing/verification problems

**Comment by akrabat** [comment]
> Oh look you're making issues for me :)

It'll certainly get lost in the Twitter stream if we don't write it down!

**Comment by l0gicgate** [comment]
> Get the count of middleware attached

> See if any middleware is attached at all

Could you provide an example with some code for the usage of this functionality? Is that being used from within the middleware pipeline itself or externally like in `index.php` when declaring your statements to boostrap your app.

> I think just incrementing a registered middleware count would help for the "is my stuff registered?" - because of the nested callable method of using the tip in the default implementation it's very hard to introspect any of the middleware data, which leads to testing/verification problems

I'd like to see an example of a test where that's being used. I can't think of why I'd need to get this information. You explicitly have to use `$app->add()` or `$route->add()` in order to attach middleware, is that not sufficient enough to tell you middleware is attached?

> Replace the stack implementation with my own that does all these things

In Slim 4 `MiddlewareDispatcher` is used in two places respectively `App` and `Route` where it is instantiated internally. The usage is currently tightly coupled to the current dispatcher's constructor signature:
- https://github.com/slimphp/Slim/blob/4.x/Slim/App.php#L89
- https://github.com/slimphp/Slim/blob/4.x/Slim/Route.php#L126

What flexibility / functionality would that provide to the end user? The only thing I can think of is wanting to change the order the middleware gets executed (LIFO or FIFO). I don't think anyone would re-implement the entire `MiddlewareDispatcher` just to get that done when all you have to do is change the order of your statements where you add middleware instead.

My opinion is that 99.9% of the users will not need this level of customization for an internally deeply nested component like that. I see very little return on the effort that would be required to make that a drop-in component.

**Comment by l0gicgate** [comment]
This issue is stale. Feel free to re-open with further input to my last comment.
