### ISSUE TITLE
Variable forced to be a \Slim\Route using vartype annotation

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2660]
The method `\Slim\Router::createRoute()` defines in its docblock that the return type is `\Slim\Interfaces\RouteInterface`. But in the following code we have to add a `vartype` annotation for the result as later on we need that the result be of type `\Slim\Route`.
https://github.com/slimphp/Slim/blob/4fa1b1b8b9af16ebed09372bb5a17b5dd5b9cff6/Slim/Router.php#L187-L190

If you would add the method `getIdentifier()` to the `RouterInterface`, then we could actually remove the `vartype` annotation.

This is cosmetics, I know. Using annotation just works fine. If you do not want to change that, then I will immediately close this issue :-)

**Comment by l0gicgate** [comment]
That method should be added to `RouteInterface` the problem is if we do that we might break something for people who've already implemented this interface. While it's probably a pretty rare case, we cannot add onto this interface because we are so deep in the release cycle.

All this is already taken care of in Slim 4 just for the record.
