### ISSUE TITLE
[4.x] Decorated Response in case of explicitly set Response Factory

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim#2709]
Hi there

## The problem

When providing a response factory explicitly to the `AppFactory::create()` method, then the response would no longer be decorated automatically. Is this the expected behaviour?

Say my `index.php` is as follows (I am using the Nyholm PSR-7 for this example):
```php
declare(strict_types=1);

use Nyholm\Psr7\Factory\Psr17Factory;
use Psr\Http\Message\RequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;
use Slim\Factory\AppFactory;

require __DIR__.'/../vendor/autoload.php';

// Explicitly define the response factory!!
$app = AppFactory::create(
    new Psr17Factory()
);

$app->get('/', function (Request $request, Response $response, array $args) {
    $response->getBody()->write(get_class($request).', '.get_class($response));

    return $response;
});

$app->run();
```

Calling the route returns
```
Slim\Http\ServerRequest, Nyholm\Psr7\Response
```
So the request gets decorated (as expected), but the response does not get decorated.

## Is this the correct solution?

In order to get the response decorated, we need to do as follows, right?
```php
declare(strict_types=1);

use Nyholm\Psr7\Factory\Psr17Factory;
use Psr\Http\Message\RequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;
use Slim\Factory\AppFactory;
use Slim\Factory\Psr17\SlimHttpPsr17Factory;

require __DIR__.'/../vendor/autoload.php';

$responseFactory = new Psr17Factory();
$app = AppFactory::create(
    SlimHttpPsr17Factory::createDecoratedResponseFactory(
        $responseFactory, $responseFactory
    )
);

$app->get('/', function (Request $request, Response $response, array $args) {
    $response->getBody()->write(get_class($request).', '.get_class($response));

    return $response;
});

$app->run();
```

The result was
```
Slim\Http\ServerRequest, Slim\Http\Response
```

If this is the way to go, then this should be mentioned in the documentation I guess. What do you think?

**Comment by l0gicgate** [comment]
This is the expected behavior. You should use the `AppFactory` if you want decoration auto detection to work.

**Comment by adriansuter** [comment]
Of course.

I was wondering how to decorate a response if it was not one of the supported PSR-7 implementations.

Then instead of passing the response factory (neither the decorated nor the non-decorated) to the `\Slim\Factory\AppFactory::create()` method, I should rather write a psr17 factory for the new PSR-7 implementation that can then be added to the psr17 factory provider using `\Slim\Factory\Psr17\Psr17FactoryProvider::addFactory()`.

Is this right? Should that be mentioned in the docs? If yes, where would that make sense? Probably this is already some advanced stuff?

**Comment by l0gicgate** [comment]
All you would need to do is create your own `ResponseFactory` and then you add it via `addFactory()` as you mentioned yes. Then it will be decorated given that Slim-Http is installed!

We should have a section about the `AppFactory` in the docs for sure. It's not really something that most people will be actively using though I suspect so I'm not sure how much effort should be poured into documenting it that thoroughly.

Edit:
After reading through the code of `AppFactory`, I think that some of the internal mechanics for decoration need to change as you pointed out:
https://github.com/slimphp/Slim/blob/4.x/Slim/Factory/AppFactory.php#L77

As seen here, `$responseFactory` and `static::$responseFactory` would not be decorated and they should be. The problem is that since the user is only passing in a `ResponseFactoryInterface` via `AppFactory::create()` we need to figure out the associated `StreamFactoryInterface` in order to create a `DecoratedResponseFactory` instance. That's not possible with the current mechanism. What we could do is add a `setStreamFactory()` method on `AppFactory`
