### ISSUE TITLE
$this-root not valid on Windows Machines

### ISSUE THREAD

**Issue by pftg** [slimphp/Slim#28]
on 203 line in Request.php used 

203: $this->root = ltrim(dirname($_SERVER['PHP_SELF']), '/') . DIRECTORY_SEPARATOR;

so for windows machine it append with symbol: '\' instead '/'

in URI used only '/' as separator, thats why little fix is:

203: $this->root = ltrim(dirname($_SERVER['PHP_SELF']), '/') . '/';

and needed to find other places where user DIRECTORY_SEPARATOR in such cases.

Thanks,
Paul

**Comment by pftg** [comment]
Forget add revision in which appear this string.

Now used:

 $this->root = rtrim(dirname($_SERVER['PHP_SELF']), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

But this is the same bug.

**Comment by codeguy** [comment]
Thanks Paul. I'll push up a fix as soon as I can.

**Comment by codeguy** [comment]
Hi Paul. I've just pushed new code that should resolve this issue. I assume you are still using either Apache or nginx on Windows, correct? I don't think Slim will work correctly yet on IIS since IIS does not provide a $_SERVER[DOCUMENT_ROOT] variable. Closing this issue, but let me know if you still have issues.
