### ISSUE TITLE
OutputBufferingMiddleware error

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#2824]
$mode = OutputBufferingMiddleware::APPEND;
$outputBufferingMiddleware = new OutputBufferingMiddleware($mode);
$app->add($outputBufferingMiddleware);

Fatal error:  Uncaught TypeError: Argument 1 passed to Slim\Middleware\OutputBufferingMiddleware::__construct() must implement interface Psr\Http\Message\StreamFactoryInterface, string given

**Comment by odan** [comment]
It looks like the `\Slim\Middleware\OutputBufferingMiddleware:class` cannot be resolved by the DIC.

```php
__construct(StreamFactoryInterface $streamFactory, string $style = 'append')
```

I guess there is just a missing container definition for `\Slim\Middleware\OutputBufferingMiddleware:class`

**Comment by odan** [comment]
It looks like the Slim 4 [documentation](http://www.slimframework.com/docs/v4/middleware/output-buffering.html) is missing the first parameter for the `$streamFactory` parameter. Maybe I create a PR to fix it.

This should work:

```php
<?php
use Slim\Factory\AppFactory;
use Slim\Middleware\OutputBufferingMiddleware;
use Nyholm\Psr7\Factory\Psr17Factory;

require_once __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

// composer require nyholm/psr7
$streamFactory = new Psr17Factory();
$mode = OutputBufferingMiddleware::APPEND;

$app->add(new OutputBufferingMiddleware($streamFactory, $mode));

// ...

$app->run();
```

If you use the  `slim/psr7` package then you could use the `StreamFactory` class:

```php
<?php
use Slim\Factory\AppFactory;
use Slim\Middleware\OutputBufferingMiddleware;
use Slim\Psr7\Factory\StreamFactory;

require_once __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$streamFactory = new StreamFactory();
$mode = OutputBufferingMiddleware::APPEND;

$app->add(new OutputBufferingMiddleware($streamFactory, $mode));

// ...

$app->run();
```

Instead of manual instantiation it would be better to add a container definition for the `StreamFactoryInterface::class` and `OutputBufferingMiddleware::class` and let the container resolve it on demand. Then it would be possible to add the middleware with a single line of code:

Example:

```php
use League\Container\Container;
use Nyholm\Psr7\Factory\Psr17Factory;
use Psr\Http\Message\StreamFactoryInterface;
use Slim\Middleware\OutputBufferingMiddleware;

$container = new Container();

// ...

$container->share(Psr17Factory::class, static function () {
    return new Psr17Factory();
});

$container->share(StreamFactoryInterface::class, static function (Container $container) {
    return $container->get(Psr17Factory::class);
})->addArgument($container);

$container->share(OutputBufferingMiddleware::class, static function (Container $container) {
    $streamFactory = $container->get(StreamFactoryInterface::class);
    $mode = OutputBufferingMiddleware::APPEND;
    return new OutputBufferingMiddleware($streamFactory, $mode);
})->addArgument($container);
```

```php
$app->add(\Slim\Middleware\OutputBufferingMiddleware::class);
```

PS: There is also a static `AppFactory::setStreamFactory` method. But I don't know how it works, because there is no `App::getStreamFactory` method. 

```php
$psr17Factory = new \Nyholm\Psr7\Factory\Psr17Factory();
AppFactory::setStreamFactory($psr17Factory);
```

**Comment by l0gicgate** [comment]
Good catch @odan.

Thank you for reporting this @SOULITY 

I'm closing this as solved as this is just a documentation issue.
