### ISSUE TITLE
Static functions - bug?

### ISSUE THREAD

**Issue by danielspk** [slimphp/Slim#2947]
Hello, why is it not possible to create groups with static functions?

Example

```php
$app->group('/example', static function (RouteCollectorProxyInterface $group) {
    // ...
}
```

This produces the following error:

**Uncaught TypeError: Return value of Slim\CallableResolver::bindToContainer() must be callable, null returned in mi_path/vendor/slim/slim/Slim/CallableResolver.php:187**

Thanks

**Comment by l0gicgate** [comment]
It’s not a bug. This is just a limitation from the php engine that doesn’t allow us to bind static closures. 

There’s no way to detect whether or not a closure is static, even through reflection, which means that if a container is present we try to bind said container to the closure so the user can use `$this` referring to it within the function body and in this case, it will throw since static closures aren’t bindable.
