### ISSUE TITLE
Preparations for PHP 8

### ISSUE THREAD

**Issue by Ayesh** [slimphp/Slim#2977]
Now with PHP 8 alpha released, I'd like to suggest that we start to test Slim on PHP 8. 

As of now, Slim 3.x only has Travis CI tests for PHP 7.3. I think we should add 7.4 first, followed by a allow-fail nightly PHP builds. 
For the PHP nightly builds, we will need `--ignore-platform-reqs` or [`--ignore-platform-req=php` if we can use Composer 2](https://php.watch/articles/composer-ignore-platform-req). 

PHPUnit 9.3 (next release) should allow it being installed in PHP 8. It is not ready yet, hence the use of `--ignore-platform-reqs`.

**Comment by l0gicgate** [comment]
Slim `3.x` is in maintenance mode only now just as an FYI.

This would be applicable for the Slim 4 branch though, we will need to bring it up to speed for PHP 8.

**Comment by edudobay** [comment]
Hi! I would be interested in helping make **Slim 4** compatible with PHP 8. (I'm not sure if I should open a new issue to discuss this, as this one was originally about Slim 3.) I already have a proposal for some small code changes that are needed, but I see that dependencies are a bigger issue to tackle and would like to understand the maintainers' view and see if I can help with that too.

The biggest issue seems to be PHPUnit, though I haven't looked so deeply at other packages that Slim depends on for testing. As for production dependencies, all of them use `>=` constraints so they seem fine for now.

To be compatible with PHP `^7.2 || ^8.0`, we must support PHPUnit 8 and 9 at the same time (PHPUnit 8 will not support PHP 8, and PHPUnit 9 requires PHP `>= 7.3`). However, as already discussed in https://github.com/slimphp/Slim/issues/2936, PHPUnit 9 deprecates `prophesize()` and to remove the deprecation warnings we must use `phpspec/prophecy-phpunit` (requires PHP `>= 7.3`).

> `PHPUnit\Framework\TestCase::prophesize()` is deprecated and will be removed in PHPUnit 10. Please use the trait provided by `phpspec/prophecy-phpunit`.

(For the record, I just got 255 of these deprecation warnings (out of 417 tests) running the test suite with PHPUnit 9.4.0.) That's why PHPUnit 9 was not adopted, as I understood from that discussion. I'm not sure how we could solve that while remaining compatible with PHP 7.2.

I don't know so much about packaging but I guess it could work with some kind of virtual package or wrapper/polyfill/backport that would make Prophecy work with PHPUnit 8 and 9 with a common interface but different implementations: for PHPUnit 8, use the bundled Prophecy and maybe an empty `ProphecyTrait`; for PHPUnit 9, use `phpspec/prophecy-phpunit`.

Other dev/testing dependencies are still lacking a `php ^8.0` declaration, so I guess there's not much we can do before they publish new releases that are declared as compatible with PHP 8? Here are they:

* https://github.com/php-fig/http-message-util
* https://github.com/Nyholm/psr7-server
* https://github.com/laminas/laminas-diactoros

**Comment by Ayesh** [comment]
I agree with the others, that our focus and efforts are better spent on Slim 4.x. 

Another suggestion (in addition to the detailed ones in the last reply) would be to use Simple PHPUnit from Symfony. It tries it's best to provide a nice middle ground so the tests can be run in various PHP versions, and I suppose a prophecy polyfill will be added too.
