### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by miraage** [slimphp/Slim#298]
Hello!
Here is no built-in CSRF protection in Slim Framework.
I offer you my helping program this feature.

Here is two ways:
1. Extending Slim_Http_Request class with some methods (getToken, checkToken etc)
2. Adding Slim_Middleware_RequestForgery (or smth like this)

Don't forget about configuration that may be:
1. Automatic protection on POST/PUT/DELETE request methods
2. User-configured parameters

Waiting for your replies.

Regards,
Mikhail

**Comment by codeguy** [comment]
I prefer this be optional middleware. Any configuration params will be on the middleware instance itself. Is this all you need to know? Let me know if you need further info. Thanks!

**Comment by miraage** [comment]
Okay. I will open new Pull Request this week.

**Comment by codeguy** [comment]
Also, this middleware will be added to the Slim-Extras repository and not into the main repository. That repo is currently undergoing reorganization, so feel free to talk with @silentworks about it, or you can send your pull request on this repo, but I'll need to manually migrate it to the Slim-Extras repo. I'd encourage you to send the pull request to the Slim-Extras repo so that you receive proper credit for your work.

**Comment by miraage** [comment]
Will be done ;)

**Comment by miraage** [comment]
https://github.com/miraage/Slim-Extras/blob/master/Middleware/CsrfGuard.php

Look at this. I think to create constants named like CSRF_KEY and CSRF_TOKEN because sometimes we don't need views (for example ajax put request).

What can you say about this?

**Comment by miraage** [comment]
Pushed by Silentworks.
Closing this.
