### ISSUE TITLE
trailing slashes on routes

### ISSUE THREAD

**Issue by hexa2k9** [slimphp/Slim#31]
Don't know how to describe this correctly, but a route `/nickinfo/` is not the same as `/nickinfo` - which actually makes no sense in case a route does not require any parameters.

Let's think about the following: A route is created like `Slim::get('foo/', $callback)` someone enteres a URL into a Browser to `http://whatever/foo` he'll get a 404, `http://whatever/foo/`on the other hand works. This should behave the same for trailing slashes. The same is for routes with parameters (e.g. `http://whatever/foo/:one/:two/`)

I of course have to say, that I'm not using the 'original' .htaccess as i really don't need a suffix '.html' for each request since I primary using json, xml or plain text as output format.

**Comment by codeguy** [comment]
Ok, so under the hood your route pattern (/nickinfo in your example) is ultimately compiled to a regular expression. So the current (undocumented) solution is to do the following (identical to the Sinatra framework's solution):

Slim::get('/foo/?', $callback);

The "?" makes the trailing slash optional and will thus call that callback with or without a trailing slash. Does this help you? If so I'll be sure to add this to the documentation.

**Comment by hexa2k9** [comment]
Yep, that works for the moment. Would be good to have that written to disk - or in this case to Git.

Anyway .. in my eyes it would be good to make a trailing slash really optional. Not just 'hacking around that' since a route is added really fast, and a callback as well - since it's just fun with Slim - but a single char is forgotten very fast (at least by me ;) ).

**Comment by codeguy** [comment]
"Yep, that works for the moment. Would be good to have that written to disk - or in this case to Git."

Do you mean added to the documentation? Or did you imply the routes' regular expressions should be cached to disk?

I think specificity is good when deciding whether or not to support trailing slashes, and that having a route with an optional trailing slash would be an edge case when making web apps that expose a specific API. In most cases you won't want a trailing slash (especially with content negotiation which will be added in version 1.1). So I'm perfectly ok with requiring a "?" to make the trailing slash optional (assuming it is well documented, of course). But I'm definitely willing to hear what you and others think. Slim's not at 1.0 yet, so I want to make sure this is done as best as possible before then.

**Comment by hexa2k9** [comment]
I've added the single "?" to my App and it works perfectly with or without the trailing slash now. That's the 'Yep'. Anyway .. it should be documented to get a great Framework (which it is already) for anyone who might run into this "Edge Case".

Now I (and all those who read Issues) know that there's a need for a "?" to ignore trailing slashes. So I for one am perfecetly OK with having this requirement.

**Comment by j4mie** [comment]
I really like Flask's approach here.

If a route is definited _with_ a trailing slash, then when the URL is entered without the trailing slash, Flask will perform a redirect. If a route is defined _without_ a trailing slash, and then is accessed with the trailing slash, Flash will return a 404. This is nice and clear, and seems to cover all the use cases.

http://flask.pocoo.org/docs/quickstart/#variable-rules

(See Unique URLs / Redirection Behaviour)

**Comment by codeguy** [comment]
This is on my radar. Going to wrap up a few other tasks then get to this. If someone else wants to jump in and take care of this, feel free.

**Comment by hexa2k9** [comment]
For the records - this currently breaks urlFor() helper. 

If a Route is created like `Slim::get('status/map/?', function ...)->name('statusmap')` and `urlFor('statusmap')` is called the URL returned is `http://whatever/status/map/?` which results in a 404 Error.

**Comment by codeguy** [comment]
@hexa2k9 Good catch. This is next on my to-do list.

**Comment by codeguy** [comment]
Here are my thoughts on a permanent solution. This example will use this route:

```
Slim::get('/foo/bar/', function () {
    echo 'Foo';
});
```

In this example, the route expects a trailing slash. When this route is requested, if the request URL _has_ a trailing slash, all is well. If the request URL _does not have_ a trailing slash, a 301 redirect response will be sent. How will this work?

In `Route::matches()`, we will convert the route pattern to a regex (lines 104-105) as we currently do. IF AND ONLY IF the route pattern has a trailing slash, we will append '?' to the end of the regex pattern so that the current request URL will match the route even if the request URL does not have a trailing slash. If the request URL matches the route's regex pattern, and if the request URL does NOT have a trailing slash, a SlimRedirectException will be thrown. This exception will be caught by the `Slim::run()` loop, and when caught, a 301 redirect response will be sent redirecting the client to the same URL but with a trailing slash.

If a route is defined without a trailing slash, and the client requests that URL _with_ a trailing slash, a 404 response will be sent. This functionality is already in place, so I don't see any issues for this scenario.

My question is, does this seem ok? It does successfully decouple the `Route` class from the `Slim` class. However, I'm not sure if relying on Exceptions in this way is the correct way to accomplish this. What are your thoughts?

**Comment by hexa2k9** [comment]
I think it's the way it should work like. Due to serendipity I got in touch with Flask (mentioned by j4mie some days ago) and could test this behaviour. That works as it should do. 

Another way could be an option on Slim's config. Something like `'trailingslashes' => '[redirect|ignore|404]'` or so. Then anyone can choose to ignore Slashes or do redirects or 404s. Means of course more work and possibly pollute Code.

**Comment by j4mie** [comment]
Flask (or, more accurately, Werkzeug - the framework that Flask is built on top of) handles this with exceptions:

http://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/routing.py#L581

So I think that's probably a good way to go.

**Comment by codeguy** [comment]
Sounds great. I'll take care of this tonight.

**Comment by codeguy** [comment]
This is done. Pull the latest code from master.

**Comment by j4mie** [comment]
Looks great, thanks Josh.

**Comment by hexa2k9** [comment]
s/looks/works/ ;)

Thanks Josh.
