### ISSUE TITLE
Support PSR-17 implementation from Guzzle/psr7 2.0 

### ISSUE THREAD

**Issue by hschletz** [slimphp/Slim#3105]
Guzzle/psr7 2.0 added its own PSR-17 implementation. http-interop/http-factory-guzzle recommends using that implementation instead.

Could we have support for the new implementation? http-interop/http-factory-guzzle could still be used as a fallback, but Guzzle/psr7 2.0 would allow dropping the additional dependency from a project.

**Comment by l0gicgate** [comment]
Yes absolutely, we should be able to do this without breaking anything!

**Comment by odan** [comment]
@l0gicgate What do you think about adding a DI container support, so that the Slim AppFactory uses the container to create and fetch the needed objects by the interface name like RequestFactoryInterface, ResponseFactoryInterface, ServerRequestFactoryInterface, StreamFactoryInterface, UploadedFileFactoryInterface, UriFactoryInterface.

**Comment by l0gicgate** [comment]
@odan we can't do that for the default behavior as not everyone may use a container since it is optional. I'm not opposed to adding that as well though on `AppFactory` as an additional feature
