### ISSUE TITLE
Bind an hook to a specific route

### ISSUE THREAD

**Issue by MirkoBonadei** [slimphp/Slim#320]
Today I am working with Slim hooks. 
Pretty cool feature. In the specific case I need to create a Thread after the HTTP response has been sent to the Client to avoid the situation in which the Server calls the Client to say "Hey, the job has been completed" before it says "202, ok I will work on it".

To do the job, I have used slim.after hook, but hooks are not specific per route, so I have to use $app to decide if I have to call the script or not (is the request triggered on that route?, is the response has been sent with 202?, is the request method POST?, ecc...), and this logic is placed inside the hook callback.
I don't like it, it is error prone. I am doing it wrong, or it could be a feature?

Mirko

**Comment by MirkoBonadei** [comment]
Update, reading the documentation, I have found this:

"This hook is invoked after the current matching route is dispatched. Usually this hook is invoked only once during the Slim application lifecycle; however, this hook may be invoked multiple times if a matching route chooses to pass to a subsequent matching route."

It seems that this is invoked on a route matching rule.... But I am not able to find any examples. It seems to be what I am looking for.

**Comment by briannesbitt** [comment]
All that `This hook is invoked after the current matching route is dispatched.` means is the hook is run IFF (if and only if) a route is matched.  So if the URI requested generates a 404 (not matching a defined route) then this hook is not called.  The hook is only called if a successful route is matched.

You could set a variable when the route is called to indicate a new thread should be started, then in the hook you can check for this flag rather than doing all of this parsing again?!?

I should also mention if you look at the source, all of the code (framework, routes, hooks etc) is ran before the body of the response is actually echo'd to the client.  The `echo $body` happens as the last statement in the `$app->run();` function so I am not sure you will get your desired timing.

I think you might have to do an implicit `flush()` after the `$app->run()` and then (maybe based on a flag being turned on) kick off your worker thread.

**Comment by codeguy** [comment]
Brian's suggestions may help you. You might also write custom middleware that, after invoking the downstream middleware layer, inspects the Request URI and, if it matches your route URI, you can fire off whatever long-running process you need.

I'm going to close this out since it is not an immediately actionable issue with the framework itself. You are more than welcome to continue this thread at http://help.slimframework.com/... you'll likely get more responses there from fellow Slim users.

Best,
Josh

**Comment by MirkoBonadei** [comment]
Many thanks guys. I really appreciated Brian's suggestions and yes, I should set a variable instead of parsing the URL again.
By the way, I have not understand why I have to call flush() even if I am using slim.after which says: "This hook is invoked after output buffering is turned off and after the Response is sent to the client. This hook is invoked once during the Slim application lifecycle."
So in this case, it seems that the Response has already been sent.
Using this hook, timings seems good, but I have to prove it under heavy traffic.

Thanks again.

**Comment by briannesbitt** [comment]
The "Response is sent to the client" just means the code executed the "echo" of body contents so you can't add any more to the Slim response body.  That doesn't mean that it has actually left the server and been sent out the socket to the client.   Hence the flush().

**Comment by MirkoBonadei** [comment]
Great. Tomorrow I will do the workaround, because now it works but under heavy load it would help my timings.
