### ISSUE TITLE
Slim 5: Enable header manipulation in ErrorRenderer/ErrorHandler

### ISSUE THREAD

**Issue by flavioheleno** [slimphp/Slim#3281]
The way `Slim\Interfaces\ErrorRendererInterface` are defined, there is no way to add/remove/change response headers, only the response body.

It would be useful to be able to manipulate a whole `Psr\Http\ResponseInterface` instance.

**Comment by l0gicgate** [comment]
I'm a bit confused by this, the error renderer's sole purpose is to render errors.

adding, removing or changing headers should be done within middleware or at the route callback level.

You can implement your own error middleware if needed to accomplish this.

**Comment by flavioheleno** [comment]
I agree that the usage of a `ErrorRenderer` is to purposefully *render* an error, but what I meant with this issue was a way to be capable of doing more than just doing the error redering, but I think you're right, I should probably deal with this in the middleware (or on a custom error handler).
The use case I had in mind was around rate-limiting, where I throw an exception that gets rendered by `JsonErrorRenderer` and lacks the rate-limiting headers.

**Comment by eerison** [comment]
just for my information, is there any branch, roadmap or milestone for slim 5?

**Comment by l0gicgate** [comment]
@eerison, there is not an official roadmap for Slim 5. I am just maintaining the many repos of the org and I have a full time job, unfortunately no time for this. If someone wants to step up and take the reigns, they are more than welcome to!

**Comment by l0gicgate** [comment]
@flavioheleno then I would suggest creating your own responder or error middleware to address this. It's not hard to extend the existing stuff to achieve what you want to do. I'm closing this as resolved.

**Comment by rotexdegba** [comment]
> just for my information, is there any branch, roadmap or milestone for slim 5?

Is there really a need for Slim 5 at this point other than using new and shiny PHP 8 features? I prefer stability and long term support over rapidly churning out new versions like Laravel and the PHP Language itself are accustomed to doing these days. As a maintainer of multiple web-apps and PHP packages, these days I just like stable packages & a micro-framework like Slim that is not constantly changing and giving me lots of work to do by constantly upgrading yearly. In the PHP world, Laravel is awesome, but their release schedule is to rapid for me to jump on board, Slim and the Yii framework have been stable and reliable and allow me to focus on developing new features in my applications instead of running the rat race of upgrading my codebases to work with the latest version of Slim. In my opinion, Slim 5 should maybe scheduled for like PHP 9 or 10. Slim 4 should continue to be maintained and made to continue working as awesomely as it currently does. 

Yii version 1, definitely deserves a medal for the number of years it's been actively supported. 👇



![image](https://github.com/slimphp/Slim/assets/1242622/46f91f7b-dcf6-4579-b073-0eba19e93b5c)
