### ISSUE TITLE
Will Slim 3.x support PHP8.1 or higher?

### ISSUE THREAD

**Issue by hashimoto-AJ** [slimphp/Slim#3292]
I use slim / 3.12.5 or want to make PHP version 8.2.
But [composer. JSON](https://github.com/slimphp/Slim/blob/fdb6d614700a4e9390c3b08dde96e1f9147ec3fc/composer.json#L46) is PHP up to 8.0.
Will Slim3.x support PHP 8.1 or more?

**Comment by odan** [comment]
The syntax `^8.0` does not mean that it's limited to "8.0". It means that it also supports 8.1, 8.2, 8.3 and so on.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by hashimoto-AJ** [comment]
My environment
Slim:3.12.5
PHP:8.2.8
OS:5.10.16.3-microsoft-standard-WSL2(on Windows11)
Docker version 24.0.5, build ced0996

I have attached the error message file, please check it.
[slim3_error.txt](https://github.com/slimphp/Slim/files/12825502/slim3_error.txt)

**Comment by odan** [comment]
This has been discussed here: #3234

**Comment by hashimoto-AJ** [comment]
Doesn't it contradict this [post](https://github.com/slimphp/Slim/issues/3234#issuecomment-1284810216)?
I think it is better not to allow versions 8.1 or higher.
Therefore, I think it should be defined as `|| 8.0.*`.
[composer. JSON](https://github.com/slimphp/Slim/blob/fdb6d614700a4e9390c3b08dde96e1f9147ec3fc/composer.json#L46)

**Comment by stemd** [comment]
Warning is **not** an (fatal) error. From [PHP manual](https://www.php.net/manual/en/errorfunc.constants.php):

_E_WARNING (int)  Run-time warnings (non-fatal errors). Execution of the script is not halted._

Warning is _future_ error.

Should version be defined as you wrote above (`|| 8.0.*`), that would mean that people which have Slim3 code and by chance upgrade their PHP to 8.1 or greater, they would need to also upgrade Slim, and not for reason that code is really not working, but because config file says so.
That simply isn't nice, if it can be avoided.

**Fact:** As is, Slim 3.12.5 supports PHP8.1 and higher.
**Opportunity:** As Slim4 is now 4 years old (2019), now is the right time to upgrade, as First Rule of Software is met = Never install new software in production. New means any software before it gets at least 2 or 3 years of upgrades.

**Comment by nqianhuiii** [comment]
brew tap shivammathur/php
brew install shivammathur/php/php@7.4
