### ISSUE TITLE
Allow encoded URIs as named routes.

### ISSUE THREAD

**Issue by deiu** [slimphp/Slim#334]
I am often working with Linked Data (semantic web) with deals with encoded URIs. For this reason I was wondering how I can use them as named routes. Currently, if I try to use a URI for a named route, I get a 404 directly from Apache.

Please consider a short example with the following route: 

http://example.com/person/https%3A%2F%2Fmy-profile.eu%2Fpeople%2Fdeiu%2Fcard%23me

In my application, I would like to define the following route: 

$app->get('/person/:uri', function ($uri) {
    echo 'Requested URI: '.urldecode($uri);
});

which would output: Requested URI: https://my-profile.eu/people/deiu/card#me

**Comment by StJudeWasHere** [comment]
I don't think this is a bug in Slim, the problem here could be caused by the %2F character which apache will automatically translate to /. You can avoid that behavior with the AllowEncodedSlashes directive:

http://httpd.apache.org/docs/2.2/mod/core.html#allowencodedslashes

Using AllowEncodedSlashes NoDecode made your example work for me. Please give it a try and confirm this.

Anyway, if for whatever cause you can't change that directive in your server I'll suggest passing the url as a query parameter.

```
// uri
http://example.com/person?uri=https%3A%2F%2Fmy-profile.eu%2Fpeople%2Fdeiu%2Fcard%23me

// then in the Slim app
$uri = $app->request()->get('uri');
```

Not as pretty but it would work too.

**Comment by ghost** [comment]
Alternatively, you could `urlencode()` it twice.  Not very pretty, but it works too.

**Comment by deiu** [comment]
Thanks! Unfortunately, both suggestions result in URIs that are not 'pretty' and conforming to REST goal of making them easy to read. I'll keep looking.
