### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by codeguy** [slimphp/Slim#48]
I am opening this issue for discussion only for now. This is a very large feature, and I would like to settle on an approach before moving to code. Post your thoughts here! I will post my own thoughts on the subject later tonight when I have more time.

**Comment by codeguy** [comment]
## Content Negotiation (CN)

CN is something I've wanted to add into Slim since the beginning. It is a very useful feature, especially for RESTful APIs. My goal is to allow Slim to produce JSON, XML, and other content using CN.

### What is content negotiation?

According to Wikipedia, CN "is a mechanism defined in the HTTP specification that makes it possible to serve different versions of a document (or more generally, a resource) at the same URI, so that user agents can specify which version fit their capabilities the best." For example, the client (a web browser) sends a request to a single URI; the request will include a "Accepts:" header that states what types of content it expects. Slim will parse the request, determine the acceptable content types, and, if possible, respond accordingly.

### Real world usage

Unfortunately, the real world is not quite that perfect. Most requests will originate from a tradional desktop or mobile web browser (ie. Firefox, Safari, Internet Explorer). Each web browser implements a slightly different "Accepts:" header format (for Internet Explorer... a much different one) making it difficult to rely exclusively on the "Accepts:" header.

Therefore, it is necessary to _fake_ CN by appending format extensions to the request URI.

```
/foo/bar.xml
/foo/bar.json
```

Because we are technically using different URIs to request the same document (albeit in a different format), this isn't considered **true** CN. But it works.

### Important Considerations

#### What if a user wants to use _true_ CN?

I intend to enable/disable _true_ CN with a Slim application setting. If true CN is enabled, the Slim framework will return content in a format determined by the "Accepts:" request header. If true CN is disabled, the Slim framework will return content in a format determined by the resource URI format extension (or a default format if no extension provided).

#### What happens if a route does not support the requested format?

The Slim framework will return a 406 Not Acceptable response whose body contains a list of URIs to acceptable and available formats (per the HTTP spec).

#### How does a route declare its supported formats?

This is up for debate. A route should be able to declare what formats it supports. So something like this:

```
Slim::get('/foo/bar', $callback)->respondsTo('html, xml, json');
```

This leads to another issue. We will need to build and maintain a mimetype registry. In the example above, "html" will be extracted and converted to "text/html". If the request indicates it accepts XML, and if the route responds to XML, an XML response will be returned. If the request does not declare a format extension (assuming true CN is disabled), then the route will respond with HTML, as it was declared first (followed by XML then JSON).

#### How are format-specific templates selected?

Template selection is delegated to the View. In most cases, I imagine a custom View will be used. So I will need to tweak the View::render method to something like this:

```
class CustomView extends View {

    public function render( $template, $format ) {
        //$template = the template file name
        //$format = the desired format
    }

}
```

The custom View class may then select the appropriate template file using whatever naming convention.

#### How is the "Content-Type:" header set based on the format?

This will occure in the `Router::dispatch` or `Slim::run` loop. I'm thinking in `Slim::run`, after the output is captured in the output buffer, and before the response is sent.

#### Error Responses

What happens if there is an error (ie. 5xx)? Currently, Slim responds with HTML. However, we may need to add in support for JSON and XML, too. How can we abstract this? How do we make this extensible to developer-defined content types?

## Thoughts?

These are my initial thoughts. Post yours here. After version 1.0 is wrapped up (refer to Road Map on the Wiki), I'll break this out into appropriate Issues and get started on it.

**Comment by KrisJordan** [comment]
I haven't looked closely enough at Slim internals to comment on philosophical/strategical choices that will plug in nicely to the framework, but I do want to highlight a few things.

Some resources which may be handy during execution from the Recess Framework:
- MimeTypes - http://github.com/KrisJordan/recess/blob/master/recess/recess/http/MimeTypes.class.php
- Accepts - http://github.com/KrisJordan/recess/blob/master/recess/recess/http/Accepts.class.php
- Accepts List - http://github.com/KrisJordan/recess/blob/master/recess/recess/http/AcceptsList.class.php

The strategy taken in Recess was to enable content-negotiation as per HTTP but to allow it to be overridden by type extensions 'resource.xml'. So the presence of ".xml" essentially forces a format.

The toughest piece to smooth over is the negotiation that happens within the framework between the router/controller and the view(s). If I'm following your example properly you're avoiding the need for 'negotiating' in-framework by saying up-front with the route "here's the route, here are the content types it will respond to". This is a fine choice, and reads quite explicitly, but has some trade-offs:
- suppose my app only deals in json & xml - it could become repetitive to have to declare this for every route
- it duplicates knowledge that is arguably the view's to keep - adding support for JSON isn't just adding a template or some new logic to a view, it's also going back and updating each route

An alternative to "a route being able to declare the formats it supports" is a "view being able to declare the formats it supports". This is the approach Recess took. When Recess added CN views added a 'canRespondWith' method so that when it came time to render, that's when the "negotiation" happened, and Recess asked the selected view "can you render this?" "no" "what about this?" "no" "what about this?" as it walked through the prioritized accept header list (or just the one forced type if an ".ext" extension was used). The main upside was that it was up to the view(s) for deciding whether they could respond. So a "JSONView" could always respond that it could render JSON, and a TwigView could look to see if there was a template with a matching extension. The main downsides are:
- It makes for a more complicated hand-off between controller and view.
- You can't respond with 'unacceptable' until _after_ the controller is handing off to view. This is potentially bad for post/put/delete requests, shouldn't matter for gets. It's not super clear in the http spec (I don't think) what to do when you can process the content of a post, but not reply in an 'acceptable' content type.

I don't think there's a right or wrong, just wanted to highlight an alternative strategy which helps tease out each's strengths & trade-offs.

**Comment by KrisJordan** [comment]
Also, in terms of dealing with the parsing of 'accept' headers, I strongly encourage reusing the code in Recess'  "AcceptsList" (linked above). The HTTP spec did a poor job designing the grammar for easily pulling out the prioritized content types. It took a bit to get this working and efficient. Usage:

```
$acceptsList = new AcceptsList(
    'text/plain; q=0.5, text/html,text/x-dvi; q=0.8, text/x-c'
);
echo $acceptsList->next(); // text/html
echo $acceptsList->next(); // text/x-c
echo $acceptsList->next(); // text/x-dvi
echo $acceptsList->next(); // text/plain
var_export( $acceptsList->next() ); // false
$acceptsList->reset();
echo $acceptsList->next(); // text/html
... etc ... `
```

Furthermore, if you're going to do other accept/content negotiation, the class "Accepts" tries to make it easy to get nextLanguage, nextEncoding, etc. from an array of headers with keys that look like 'ACCEPT', 'ACCEPT_LANGUAGE', 'ACCEPT_ENCODING', and 'ACCEPT_CHARSETS'.

Which brings up another dimension of content negotiation: negotiating encodings for gzip, etc. Ideally this happens as middleware and your controllers/views are ignorant of this decision.

**Comment by codeguy** [comment]
This feature is on hold for the time being (still a part of 1.1). I want to take some time to further research this on my own before moving forward with implementation.

**Comment by lukemorton** [comment]
Just some passing thoughts.

Shouldn't accept headers be part of a wider, more full support for routing conditions based on HTTP request headers? So like you use ->conditions() you can also use ->headers(). For example:

```
// Our HTTP header compliant route
Slim::get('/query/:datasource', function () {
    // lalalala
})
    // Route conditions
    ->conditions(array(
        'datasource' => '(a|b)'
    ))

    // Header conditions
    ->headers(array(
        'Accept' => 'application/(json|xml)'
    ));
```

To save the repetition you could use a public statics for both conditions and headers like so:

```
Slim::$conditions= array(
    'foo' => 'bar' 
);
Slim::$headers = array(
    'Accept' => 'application/json'
);
```

Then the final conditions and headers would be a merge of the defaults and individual route defined conditions and headers.

Of course you could add a higher level accept to header conditions as you have provided in your example with ->respondTo() but I think it could be clearer with a method called ->acceptType(), because pretty much every part of a route definition defines what the application should "respond to".

This still does not provide a solution to the problem of non-compliant accept headers.

**Comment by lukemorton** [comment]
I think any solution to the non-compliant accept headers will be inelegant and misleading to some. For example if you allow extensions to be used this will not be clear unless defined within the route itself, which too will lead to repetition.

I guess you could have something that checks for extensions particularly? If a route is defined with an extensions method then this will require the use of an extension or the equivalent Accept header?

```
Slim::get('/data', function () {
    // accepts /data.json, /data.xml or /data with appropriate Accept header
})->extensions('json, xml');
```

I'm still not happy with this solution however.

**Comment by codeguy** [comment]
Closing this out. There's some great conversation here and will consider everything above when I begin working on the conneg implementation soon.

**Comment by BigBlueHat** [comment]
Looks like this has been percolating for some time, but wanted to throw in my meager $0.02. :)

I was actually headed here to file to issues: 1) for Accept header (at least) conneg 2) for file extension routing (as I'm "replicating" an API in Slim which uses those)

For the first, I'd love to see a syntax something like:

``` php
$app->get('/thing', function() {
  // do some data gathering stuff
  // and then hand it off to the chained function
  // *don't* (ideally) output anything but (maybe) headers here
  return $data;
})->accept('application/json', function($data) {
  // assuming the Accepts header matches the mimetype
  // use the passed in $data likely via a template
  // to echo/send back this data and finish the connection
})->accept(array('text/html', 'application/xhtml+xml'), function($data) use ($app) {
  // same as the above, but for two mimetype options
  // these could use a named "shortcut" type like "html" (re: Recess)
  // and the specific mimetype could be used conditionally here
  // to "tidy" or otherwise tweak the format distinctions between html and xhtml
  $html = template($data);
  if (in_array('application/xhtml+xml', explode(',', $app->request()->headers('Accept'))) {
    echo tidy_repair_string($html, array('output-xhtml' => true));
  }
});
```

Please note: due to the presence of the quality param in Accepts (ex: "_/_;q=0.8") the explode() above won't work. Just an FYI. :)

Not sure if it's "ideal," but I like the fluent interface use and the feeling of munching data in the first part ($app->get(), and dealing with output format issues in the second part (->accept()). I also think using "accept" as the method names aligns more closely to what one sees "on the wire" when using HTTP--which is a perk, maybe, but one I like. :)

So, there it is. Roughly $0.02. ;)

Thanks.

**Comment by njh** [comment]
I needed Content Negotiation for a project I am working on, so I have implemented it in a branch:
https://github.com/njh/Slim/tree/negotiation

Even if it doesn't get accepted into Slim master, hopefully some of the code will be re-usable and there is something that can be used in the meantime.

See #376 for details.
