### ISSUE TITLE
Path mangling when using mod_rewrite

### ISSUE THREAD

**Issue by doublemarked** [slimphp/Slim#521]
Hello,

Today I've been trying to get Slim to do something that I expected to be very simple, but have had some trouble. I stuck my Slim setup under a subdirectory named `app/`, and adjusted my Rewrite rule as follows: 
   `RewriteRule ^ app/index.php [QSA,L]`

Note, everything works fine without mod_rewrite, and my URLs look like:
   `http://www.domain.com/app/index.php/hello/world`

Surprisingly though, with the rewrite rule, I find that all of my routes now require an /app prefix on them:
   `http://www.domain.com/app/hello/world`

This feels kind of fishy. I am not familiar with the codebase, but I poked around a bit in Environment.php, and came across the following, [starting at line 144](https://github.com/codeguy/Slim/blob/4d85e993/Slim/Environment.php#L141-L149):

```
            if (strpos($_SERVER['REQUEST_URI'], $_SERVER['SCRIPT_NAME']) === 0) {
                $env['SCRIPT_NAME'] = $_SERVER['SCRIPT_NAME']; //Without URL rewrite
            } else {
                $env['SCRIPT_NAME'] = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'])); //With URL rewrite
            }
            $env['PATH_INFO'] = substr_replace($_SERVER['REQUEST_URI'], '', 0, strlen($env['SCRIPT_NAME']));
```

This last line seems actually quite wrong when there is a URL rewrite. As we know from the previous conditional, REQUEST_URI does not start with SCRIPT_NAME, yet we rip apart the front of REQUEST_URI based on the length of SCRIPT_NAME. 

I made a patch to fix this, which simply assigns REQUEST_URI to PATH_INFO when a URL rewrite is being used (when the conditional is false):

```
            if (strpos($_SERVER['REQUEST_URI'], $_SERVER['SCRIPT_NAME']) === 0) {
                $env['SCRIPT_NAME'] = $_SERVER['SCRIPT_NAME']; //Without URL rewrite
                $env['PATH_INFO'] = substr_replace($_SERVER['REQUEST_URI'], '', 0, strlen($env['SCRIPT_NAME']));
            } else {
                $env['SCRIPT_NAME'] = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'])); //With URL rewrite
                $env['PATH_INFO'] = $_SERVER['REQUEST_URI'];
            }
```

This fixed my setup, but broke several unit tests, including the following [from EnvironmentTest.php](https://github.com/codeguy/Slim/blob/4d85e993e8cdeac6f50c11d60d81dfb1aa8ad44a/tests/EnvironmentTest.php#L141-L149):

```
    public function testParsesPathsWithUrlRewriteInSubdirectory()
    {
        $_SERVER['SCRIPT_NAME'] = '/foo/index.php';
        $_SERVER['REQUEST_URI'] = '/foo/bar/xyz';
        unset($_SERVER['PATH_INFO']);
        $env = \Slim\Environment::getInstance(true);
        $this->assertEquals('/bar/xyz', $env['PATH_INFO']);
        $this->assertEquals('/foo', $env['SCRIPT_NAME']);
    }
```

This test creates an environment where REQUEST_URI is /foo/bar/xyz, but produces a PATH_INFO that lacks the /foo component. This produces a scenario where the path URL used in a Route would not properly match its request URI. This feels fishy. 

I'm not sure how to proceed. I'm not familiar enough with the codebase to be submitting pull requests that modify both code and tests. It may be that I've made a logical mistake somewhere, and welcome any correction.

Please advise, either on what should be done or where my logic has gone awry.

**Comment by xjunior** [comment]
I didn't write tests, I was just trying to get that done for myself, but I believe that #475 doesn't break other situations IIRC.

**Comment by doublemarked** [comment]
Hmm. I ran your branch through phpunit. It seems kinda broken. Your preg_replace call is missing a regex, and it's erroring out on a bunch of tests. I will write some advice on your ticket about this.

**Comment by codeguy** [comment]
I'm going to leave it as is right now.

**Comment by doublemarked** [comment]
Does that mean you consider it working properly?

**Comment by codeguy** [comment]
Yes, for now.

**Comment by doublemarked** [comment]
It's a mysterious way of describing whether something works as intended or not :) What do you mean by "for now"?

**Comment by xjunior** [comment]
I guess he meant to say that it's a feature planning for the future.

**Comment by silentworks** [comment]
Hi @doublemarked your feedback will be taken into consideration. I think that as it currently stands it is considered to be working correctly. This will probably get looked at in the next major point release.

**Comment by devios1** [comment]
Why is this not considered a bug? Especially when the fix is so simple. I just spent an hour digging through code to figure out why my server was all of a sudden broken after updating my mod_rewrite rules. The lesson here is that you can't assume `$_SERVER['REQUEST_URI']` is based on `$_SERVER['SCRIPT_NAME']`, and this assumption breaks otherwise fully legit environments.

Thanks to doublemarked for the report and fix, though I actually came here to report the very same bug, having discovered it on my own as well. :)

**Comment by doublemarked** [comment]
Thanks. It's nice to hear I'm not the only one seeing it this way...

**Comment by tuupola** [comment]
When you put your app into subdirectory why not just use?

```
RewriteBase /somedir/
```

Works without any problems.

**Comment by devios1** [comment]
I'm no mod_rewrite expert. I tend to get things working and leave it alone. :) I seem to recall attempting to use RewriteBase in the past without success, however, but not pertaining to this issue. I will give it a shot and see.

**Comment by devios1** [comment]
Quick investigation looks like `RewriteBase` is meant primarily to target a specific subdirectory for rewrites, however I'm not sure it can be used to _hide_ a directory from the url, which is my primary reason for using mod_rewrite. For example, I have my site organized into a subdirectory `/site`, but want `http://host.com/whatever` to invisibly map to `http://host.com/site/whatever`. It doesn't look like `RewriteBase` can do this, because the rule needs to apply one level up and redirect _into_ that subdirectory. If you target `/site` with RewriteRule, the rule will not get applied on `/`.

**Comment by tuupola** [comment]
You are correct. `RewriteBase` is kind of base href of mod_rewrite rules. It sets the base folder for all following rewrite rules in the .htaccess file.

Do I  understand correctly you have a Slim application in `http://host.com/site/foo` but you want it to appear in `http://host.com/foo`?  Just install the slim application directly to `http://host.com/foo` and there is no need to use mod_rewrite rules.

**Comment by devios1** [comment]
Well kind of the whole point is that I _want_ it in `/site/foo`. My web host doesn't allow the base account domain to point to a subdirectory (for some reason, I guess cPanel doesn't support it or something), however I have several different sites hosted on the same account via add-on domains, each of which points to a subdirectory of root. I don't want to have my main site at root sort of mixed in with all the different other site subdirectories, so I use mod_rewrite to redirect the main domain to its own isolated subdirectory and all is happy. It is a bit of a pain to deal with mod_rewrite, but I prefer it over the alternative.

At any rate, I've modified Environment.php so that it will work with my environment (hmm, ironic?), as per doublemarked's solution so this is working fine for me now. I'm merely pointing out that it really should be considered a bug, as there will probably be others who run into the same problem.

**Comment by silentworks** [comment]
I will run some test on this along with your changes on a few different environments and see if it behaves the same, especially on IIS. Once this works correctly I will try and get it resolved.

**Comment by q3452** [comment]
chaiguy's fix is pretty good but there are some edge cases that it doesn't cover.

In the extremely common design pattern that uses some version of:
/
/public
/lib

We need to rewrite twice, once to add public (if necessary) and once to add index.php (if necessary).
It's the "if necessary" that is the problem.

The existing code handles:
    example.com/public/index.php/dostuff
and
    example.com/public/dostuff
but breaks on:
    example.com/index.php/dostuff
    example.com/dostuff

The code from @chaiguy is a vast improvement but although it handles the useful cases of:
example.com/dostuff works
example.com/public/index.php/dostuff
It breaks on the pathological cases below:
example.com/index.php/dostuff
example.com/public/dostuff

This isn't a show stopper since fixing a huge bug but creating a small one is still an improvement and I can live with pathological cases if I don't have to manually patch library code for my business-as-usual ones.

**Comment by silentworks** [comment]
Can you test this is 2.3.5 release of Slim, this should now be fixed.

**Comment by gregelin** [comment]
I had a similar need to run Slim inside a sub directory. I liked the fact @doublemarked discovered everything worked if one simply appended the path to the subdirectory to all the routes. I found simply doing that to be an acceptable solution.
