### ISSUE TITLE
Website has no language set

### ISSUE THREAD

**Issue by neilstuartcraig** [slimphp/Slim#539]
Hi

I've just found Slim and haven't yet given it a go but it looks great, nice work!

Just a minor point - on the website, there's no language meta info so Chrome has decided it's Galician. Just thought i'd raise the point.Screenshot attached
![slim](https://f.cloud.github.com/assets/320215/630696/c89143d0-d1ae-11e2-80a2-77ed163aa879.png).

Cheers

**Comment by codeguy** [comment]
Thanks for the heads up. We've run into this before and adding a "lang" attribute to the HTML element did not seem to fix it (although this issue may have been fixed in a recent build of Chrome). I've re-added the lang attribute so hopefully that will fix it. The issue was narrowed down to one of the contributor names.

**Comment by nickshanks** [comment]
I reported this back to chrome as a bug in their language detection (using the "report incorrect detection" menu item, not a crbug).
