### ISSUE TITLE
nginx Configuration

### ISSUE THREAD

**Issue by nielsen** [slimphp/Slim#55]
I've been having some trouble getting Slim to play nice with nginx; the site at the root is implementing Slim, but the sub-folders have other apps (Wordpress for example).

This is what I have so far; any thoughts?

```
    location / {
        index bootstrap.php;
        try_files $uri $uri/ /bootstrap.php; 
       # the working WP configuration takes ?q=$1 parameters; should Slim as well?
       # try_files ~ if ( !-e $request_uri ), only less taxing.
    }
```

**Comment by codeguy** [comment]
I am unfamiliar with nginx configuration, which is why I've recommended Apache for Slim. I do know that one of the Slim contributor's (hexa2k9) had created a working nginx configuration file for Slim. See this commit:

https://github.com/codeguy/Slim/commit/4747f4c84e3ef682bd6571df7fb68f6be218c7a1

I'm closing this out since it's not really an issue with Slim. But feel free to leave additional comments if you have any further questions.

**Comment by dmtrs** [comment]
@nielsen :+1:
