### ISSUE TITLE
Can we do something to avoid "html arrays"

### ISSUE THREAD

**Issue by tutuca** [slimphp/Slim#56]
Sort of question/feature request. 

It would be possible for slim to map multiple form fields with the same name to an Array without the need to add square brackets in the html (as per this [manual page](http://www.php.net/manual/en/faq.html.php#faq.html.arrays))?.

**Comment by lukemorton** [comment]
What is the problem with using square brackets in your HTML?

**Comment by tutuca** [comment]
As far as I know they are not mentioned anywhere in the spec. And they are just plain ugly :)

**Comment by codeguy** [comment]
I don't think I am going to implement this feature. It's already common (and recommended) practice to use square brackets to pass information as an array from HTML into PHP. I'd rather not change the recommended approach in Slim since this would likely confuse developers and deviate from standard practices. I think the "ugliness" can be easily mitigated by isolating the given markup in a Twig macro or a Smarty/Mustache macro/partial equivalent. Closing this out for now, but feel free to leave further comments if you want.
