### ISSUE TITLE
Update Environment class

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#633]
Does the Environment class need to be static now as we have the IoC container? Can this not be altered to not return a static instance, but be a normal class now.

Also, it would be quite useful to update this to extend the `NestedArrayHandler` I provided in the Configuration PR, as they both use nested keys.

**Comment by codeguy** [comment]
You bring up a good point. The \Slim\Environment class was originally static because it parsed and dealt with information readable only once (particularly the request body from php://input). However, I agree it should be changed. I'm not entirely sure it will need the NestedArrayHandler, but I'll keep that in mind if I see that it does. I'll assign this to me and take care of it later this evening.

**Comment by codeguy** [comment]
This is done https://github.com/codeguy/Slim/commit/79790012c98837e75446e04a753fbe79d8c46409
