### ISSUE TITLE
No FlashTest

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim#712]
There is no test for the Flash class :(

**Comment by designermonkey** [comment]
Is this because Sessions don't work on command line?

**Comment by codeguy** [comment]
Still needs to be written.

**Comment by charlie-s** [comment]
Initial tests here: https://github.com/csdco/Slim/commits/flash-test

Mostly matches the previous Flash test, updated for syntax, methods, \Slim\Session, etc. All tests passing, but the session usage isn't quite right in the 3rd and 4th tests. I need to follow @codeguy's message from https://github.com/codeguy/Slim/issues/713 to mock the Session dependency and give that a go.

**Comment by charlie-s** [comment]
Okay, refactored the Flash test to use Mockery and all are passing:
https://github.com/csdco/Slim/commit/99b8ca9e830af46b897769716099aa189a4365ae
https://travis-ci.org/csdco/Slim/jobs/16387322

A couple of things...

1) I wanted to get the latest code from the `develop` branch, so I followed the accepted answer at http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository to rebase `develop` into my `flash-test` branch. This means my fork now has a big merge commit (https://github.com/csdco/Slim/commit/2a65c13b0b85a22d06d28c78991a5ec1c62f5f15). Is that the recommended way to do it, or does it muck up an eventual merge back into the primary repo?

2) SessionHandlerInterface is missing a semicolon after the namespace declaration (https://github.com/codeguy/Slim/blob/develop/Slim/Interfaces/SessionHandlerInterface.php). This is in the current `develop` branch. My tests obviously wouldn't run without it, but I didn't include it in my commit since that fork should be feature-specific.

@codeguy Mockery is cool – thanks for suggesting I write the tests with it. Implementing the Session class with a dummy dataObject / `\ArrayObject` is a great idea, too.

**Comment by charlie-s** [comment]
@designermonkey Any idea on (2) above? How are tests running successfully for other folks if https://github.com/codeguy/Slim/blob/develop/Slim/Interfaces/SessionHandlerInterface.php has that syntax error? (I'm really just curious.)

**Comment by designermonkey** [comment]
When it comes to a simple fix like that, I would just add it to your branch. I'm sure @codeguy will pull it shortly anyway.

I hadn't noticed it failing myself, not sure why.

I rebase too, but how it is supposed to be done in this project would be up to Josh.

**Comment by charlie-s** [comment]
Thanks Josh, I've added that and submitted via https://github.com/codeguy/Slim/pull/724. Will continue the conversation there.

**Comment by codeguy** [comment]
Sounds good. I'm not a super advanced Git user... I just do what appears to accomplish my goal and carry on :) I'll mess with it and see if I need to do anything to merge.
