### ISSUE TITLE
Best ORM for use w/Slim ??

### ISSUE THREAD

**Issue by andyl** [slimphp/Slim#72]
I'm new to PHP and slim looks like a nice Sintra-like framework.

IYHO what is the best ORM to use in conjunction with Slim ??  (10 tables, 200 records per table, many joins, prefer sqlite)

(ps I would have asked on IRC but couldn't find anyone in #slim or ##slim...)

Tx, Andy

**Comment by Wemago** [comment]
https://github.com/jasonmoo/DumbledORM

maybe this could be a good option for you, uses PDO, so you can do sqlite

**Comment by codeguy** [comment]
No worries. I usually hang out on IRC, but I've been in and out with the holidays. Best light-weight PHP ORM... I would take a look at @j4mie's [Idiorm/Paris](http://j4mie.github.com/idiormandparis/) combo. It's relatively new, works well, and provides you a simple light-weight solution. [@KrisJordan](http://www.github.com/KrisJordan) has also unofficially abstracted the excellent ORM from his [Recess Framework](http://www.github.com/recess/recess)... you might ping him about that. Closing this out, but don't hesitate to leave further comments if necessary. Thanks!

**Comment by andyl** [comment]
Thanks these are all great suggestions.  

Do either of you have an opinion on Propel ORM ?? (http://www.propelorm.org/)

**Comment by codeguy** [comment]
@andyl I have never used Propel, but I know that it and Doctrine are very capable and mature ORMs. However, they are both very robust in a _everything-but-the-kitchen-sink_ kind of way. If you need something like that, Propel or Doctrine will work great. If you are looking for sweet and simple (Slim's goal), Idiorm/Paris or DumbledORM is the way to go :)

**Comment by andyl** [comment]
OK - I will give Idiorm/Paris a try - thanks again for your feedback !!

**Comment by tobsn** [comment]
i use ActiveMongo

**Comment by ybelenko** [comment]
Any changes in 2020? :smile:

Slim3 documentation contains [Using Eloquent with Slim](http://www.slimframework.com/docs/v3/cookbook/database-eloquent.html) section, while Slim4 have no mentions of any ORM at all.

I understand that Slim team won't provide ORM system from the box because it's out of the project scope, but you can at least recommend something based on your personal experience. Any guides related to Slim4 + ORM would be great and really helpful.

UPD: Just noticed that there was also [Using Doctrine with Slim](http://www.slimframework.com/docs/v3/cookbook/database-doctrine.html) and [Using Atlas 3 with Slim](http://www.slimframework.com/docs/v3/cookbook/database-atlas.html).
