### ISSUE TITLE
Switch to Symfony HTTP Foundation

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim#776]
What about switching to use Symfony HTTP Foundation.
After reading you article in O'Reilly about New PHP, it makes sense.

**Comment by jamesmoss** [comment]
I've wondered about this too as I'm a big fan of HTTP Foundation. Its a pretty comprehensive component but I think it's too heavy for Slim and kinda goes against the projects goal.

**Comment by codeguy** [comment]
Using my article against me I see ;) No, I agree Slim should adopt an existing component. I think I want to wait, though, until the PHP-FIG releases a new PSR specifically for HTTP request and response interfaces before making this decision.

**Comment by codeguy** [comment]
Also, even with a new PSR, I think Slim will still ship with a very "slim" implementation with only a few core methods required by the interface. This will make it easier to swap in a more robust implementation like HTTP Foundation if you want.

**Comment by ghost** [comment]
I don't remember if Http Foundation has interfaces for Request and Response.

If not, they should be proposed.

**Comment by codeguy** [comment]
@ramirovjr I think we can get this into 3.0 (currently the develop branch). To get this started, can you figure out the most important methods used by HTTP Foundation's request and response classes and list those here? We can use those to refactor and simplify Slim's current request and response classes.

**Comment by designermonkey** [comment]
Any help required, give me a shout.

**Comment by ghost** [comment]
I think that these methods is what matters most (correct me if I'm wrong):

**Request**
- References:
  - http://blog.servergrove.com/2013/09/23/symfony2-components-overview-httpfoundation/
  - https://github.com/symfony/HttpFoundation/blob/master/Request.php
- Methods and Properties
  - create(string $uri, string $method, array $params)
  - getClientIp()
  - getMethod()
  - getPathInfo()
  - getBasePath()
  - getRequestUri()
  - getHttpHost()
  - getContentType()
  - getLocale()
  - getContent() (content body)
- Questions
  - Are we going to enable fetching request parameters from the request object (ex.: $request->query->get()) or an outside method?

**Response**
- References:
  - http://blog.servergrove.com/2013/09/23/symfony2-components-overview-httpfoundation/
  - https://github.com/symfony/HttpFoundation/blob/master/Response.php
- Methods and Properties
- $headers
  - set(string $key, string $value)
  - get(string $key)
- send()
- setContent(mixed $content)
- setCharset(string $charset)
- setStatusCode(int $status)

Beside those mentioned, we cannot forget about the HttpKernelInterface, which would be nice to use, as others are also using - Drupal, Laravel, ... - and would enable component switching.

**Comment by ghost** [comment]
I think that this question that I'm going to make, should be moved to a next topic, but let's see:

Like other components and frameworks, Silex - which is also a microframework - has the StackBuilder, which can be used to enable middlewares (like plugins). What about this same idea in Slim? If we can get to a similar approach, these components will be available for both frameworks.

And please, I'm not saying that this should be implemented - it's just an idea to avoid duplicating components.

**Comment by codeguy** [comment]
Let's move that to a separate issue.

**Comment by codeguy** [comment]
The problem with HttpKernelInterface is that it has a hard dependency to `Symfony\Component\HttpFoundation\Request` as far as I can tell. This is the reason we need a PSR for HTTP request and response interfaces.

**Comment by codeguy** [comment]
But thanks for the research notes above. I'll have a look tonight and put together a game plan.

**Comment by ghost** [comment]
Ok, no problem.

If there's anything that I can help, please don't hesitate.

**Comment by codeguy** [comment]
For sure. I intend to have you heavily involved in this transition. Just fyi, there is this php-fig proposal here, but it has not opened up for public discussion just yet.

https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md

**Comment by lalop** [comment]
Really interested too, if I can help for something give me a shout

**Comment by ghost** [comment]
In the issue that I created in the Symfony project, Fabien said it make no sense to create an interface for data objects.

So, with this in mind, I think that using the HttpKernelInterface will be hard, because of the Request dependency.

**Comment by anlutro** [comment]
The hard dependency to the Request/Response classes do not need to encompass the entire application. As long as your `handle` method accepts and returns the correct objects, you can do any amount of transformation and abstraction in-between.

For example, you could write a proxy class that has an underlying Symfony Request/Response object but provides a simplified or more framework-tailored interface, and then just call a method that returns the underlying Symfony response object before `handle` returns it. The application's route controllers could then deal with these response/request classes instead of the symfony ones (which are quite clunky).

Another huge advantage of the HttpKernelInterface is how easy it becomes to write functional tests for your application. See [Silex's WebTestCase](https://github.com/silexphp/Silex/blob/master/src/Silex/WebTestCase.php) as an example - this way of setting up a test will work with _any_ application that implements the HttpKernelInterface.

I don't know how far off the PSR is, but I imagine that if/when it is implemented, it will work similarly to how symfony's response/request objects work currently, so if one were to implement symfony's classes now, transitioning to the PSR ones later on would be pretty easy.
