### ISSUE TITLE
[BUG] Post request not parses correctly

### ISSUE THREAD

**Issue by nicknill** [slimphp/Slim#780]
```
$app->request->params() 
```

did not works correctly when using content types middleware.

**Comment by mackenza** [comment]
pretty sure this will require more information than provided to be taken seriously as a bug

**Comment by codeguy** [comment]
Yep. I'll need much more information to go on here.

**Comment by nicknill** [comment]
Steps to reproduse:
1. Add content types middleware
2. Send request to slim, for example, in JSON format with setting content type
3. Look at var_dump($app->request->params()) - it's empty.

Here is a patch i make for a workaround.

```
class ContentTypes extends \Slim\Middleware\ContentTypes {

       public function call() {
        $mediaType = $this->app->request()->getMediaType();
        if ($mediaType) {
            $env = $this->app->environment();
            $env['slim.input_original'] = $env['slim.input'];
            $env['slim.input'] = $this->parse($env['slim.input'], $mediaType);
            if(is_array($env['slim.input']))
                $env['slim.request.form_hash'] = $env['slim.input'];
        }
        $this->next->call();
    }
} 
```

**Comment by mattzuba** [comment]
Have you looked at the ContentType tests to see how that middleware is intended to be used (getBody(), not params())?  https://github.com/codeguy/Slim/blob/master/tests/Middleware/ContentTypesTest.php

**Comment by nicknill** [comment]
I see it, but why it is not request params?

**Comment by mackenza** [comment]
what are you looking to `var_dump` in the `request->params()`?  i.e. what are you trying to get out of it?  For a json request I would expect to get this via `getBody()` as shown, but if it's not the body you are trying to get, it would help to know what your expected results were.

**Comment by nicknill** [comment]
The main question is why json, xml, etc, is not request parameters? or in other words not in request->params()

**Comment by lplume** [comment]
nicknill did a good question. Let's take a look at Slim\Http\Request; the doc for the function params() is: "This method returns a union of GET and POST data as a key-value array, or the value of the array key if requested; if the array key does not exist, NULL is returned.", internally it uses post() and get() method.
function post(): "This method returns a key-value array of data sent in the HTTP request body, or the value of a hash key if requested; if the array key does not exist, NULL is returned."; actually data sent in HTTP request (like a form for example) has its own content type (multipart ecc) and the data is within the request body.
while
function get(): "This method returns a key-value array of data sent in the HTTP request query string, or the value of the array key if requested; if the array key does not exist, NULL is returned." which is diffrent, get data are query string (www.something.yolo?query=string).

The HTTP header contettype is meant to identify the media type sent in the request body. Think of SOAP web services: your request is an xml in the request body, the soap services looks for an xml in the request body.

To clarify your question, basically the ContentType Middleware could be expanded to parse content-type multipart/form-data; and this ideally could deprecate function post() method in the Request class (be careful, this is madness, but the intention is to explain why to call getBody() instead of params() )

**Comment by nicknill** [comment]
It's better to not deprecate function post(), but give parsed request body by ContentType.
As for me, i think getBody() should always give unparsed body, and params() or post() give parsed params from body

**Comment by m1ga** [comment]
Sorry for bringing this back up again, but $app->request->params() is still empty in middleware. I found this one: http://help.slimframework.com/discussions/problems/7766-get-postget-parameters-in-middleware?unresolve=true but it would be nice just to use params() to get both GET or POST

**Comment by codeguy** [comment]
Resolved in dev branch.
