### ISSUE TITLE
Error is causing only blank page to be returned.

### ISSUE THREAD

**Issue by SargentHatch** [slimphp/Slim#80]
Consider this code:

```
Slim::get('/myurl/:varA/:varB', function ($varA, $varB) {
include '/models/otherVars.php';
Slim::render('var.php', array('varA' => $varA, 'varB' => $varB, 'varC' => $varC, 'varD' => $varD));
});
```
1. Is it "correct" to include '/models/otherVars.php' such as I am?
2. While writing /models/otherVars.php, I left out a ; at the end of a line and the framework rendered a blank page - no error was thrown. Once I noticed the typo, I corrected it and all was well. Then I put a simple $d = 1/0; in /models/otherVars.php to see what would happen. The framework threw a divided by zero error. Why didn't the framework throw an error when I left out the ; at the end of a line?

**Comment by codeguy** [comment]
Interesting. I'll take a look tomorrow and see what I come up with. Thanks!

**Comment by codeguy** [comment]
@FredWilson I'm unable to duplicate this issue here. As I'm sure you know, and I'll repeat here just for later reference, if you `include()` a file with an error, PHP will issue a warning and continue executing the script; however, if you `require()` a file with an error, PHP will generate a fatal error and kill the script.

To answer your question, yes, you should be able to `include()` a script as you've done in the example above. I've performed my own tests locally including a PHP script with errors in it, and the application continued to render the page as expected. Can you post the full content of the included PHP file in your example above so my tests can match yours as closely as possible?

**Comment by codeguy** [comment]
@FredWilson Some additional notes. After adding syntax errors to the included PHP file, PHP is throwing a Parse Error (which is not catchable by the PHP script). Syntax errors are beyond my control. Slim is able to respond to a divide-by-zero error.

**Comment by codeguy** [comment]
@FredWilson Unable to properly duplicate on my end. Closing this out for now. Please post additional details so I can duplicate this issue and fix it if necessary. Will re-open at a later date once you have more details. Thanks!

**Comment by SargentHatch** [comment]
Sorry for the delayed response.  Thanks for checking into this.

My web host does not allow: error_reporting = E_ALL

That's it really.  On my localhost, I changed the php.ini and syntax errors showed up no problems.

More experienced PHP users will get this right away.  I assumed that Slim handled all errors, but I understand now why it cannot.

Thanks for checking into this.  The framework seems really nice so far.
