### ISSUE TITLE
log.writer non-string(able) values.

### ISSUE THREAD

**Issue by guice** [slimphp/Slim#840]
Per the documentation:
http://docs.slimframework.com/#Logging

> Each log object method accepts one mixed argument. The argument is usually a string, but the argument **can be anything**. The log object will pass the argument to its log writer. It is the log writer’s responsibility to write arbitrary input to the appropriate destination.

However, per the code, "mixed" parameter has to be a string or string-able object, preventing the ability to send arrays (even though a log writer, such as php-console, can support arrays). 

https://github.com/codeguy/Slim/blob/master/Slim/Log.php#L309

``` php
            $message = (string)$object;
```

Any attempt to send an array or non-stringable object results in an error.

**Comment by guice** [comment]
Interesting. I didn't even realize there was a PSR specific to logger interfaces.

I agree with your assessment. The dirty fix doesn't work very well--key issue being when context has data, the interpolate replace blows up with (again) non-string data.

I would add one more patch in checking "is_array()" on $context before assuming array. Php-Console--the logger I was using--and old ZF1 (ZF2? Maybe has changed now), supplied their messages as: ([mixed] $message, [string] $label = null). Supplying a string into $context will cause interpolate call to fail.

**Comment by bensquire** [comment]
This is also causing me some issues as I'm trying to pass an array into my custom LogWriter...

**Comment by hakre** [comment]
That shouldn't be an issue, array is converted to string in PHP as "`Array`". Perhaps not what you want or expect, but that's how that code works. I remove my other comments as this Slim seems dead and I don't wanna put any hurdles.

**Comment by bensquire** [comment]
This line means I cannot pass an array into my custom log writer or am I missing something?

```
https://github.com/codeguy/Slim/blob/master/Slim/Log.php#L309
```

Also (and this may be a stupid question) but what do you mean by "this Slim seems dead"

Thanks :)

**Comment by tuupola** [comment]
Not directly related, but I have been using [Monolog](https://github.com/Seldaek/monolog) which is PSR-3 compliant with Slim for a while. Something like:

``` php
/* Setup Slim */
$app = new \Slim\Slim();

/* Setup Monolog */
use Monolog\Logger;
use Monolog\Handler\RotatingFileHandler;
use Monolog\Handler\PushoverHandler;
use Monolog\Formatter\LineFormatter;

$log = new Logger("slim");
$formatter = new LineFormatter("[%datetime%] [%level_name%]: %message%\n");
$rotating  = new RotatingFileHandler(__DIR__ . "/logs/slim.log", 0, Logger::INFO);
$pushover   = new PushoverHandler("xxxxxxxxxx", "xxxxxxxxxx", null, Logger::ERROR);

$rotating->setFormatter($formatter);
$log->pushHandler($rotating);
$log->pushHandler($pushover);

/* Attach Monolog to Slim. */
$app->log = $log;
```

**Comment by silentworks** [comment]
@hakre Slim isn't dead, but as devs we also have other responsibilities, I have just recently taken the time to help @codeguy with dealing with some of these PRs but us not taking in your PR in your set timeframe doesn't mean the project is dead. We are also working on Slim 3 as we keep maintaining 2.

@bensquire Slim isn't dead, you will probably be better with using the solution @tuupola suggested for Loggers in Slim. In the Slim 3 it is likely we will be using Monolog to benefit from its more advanced features and its community. I will find out from @codeguy about PR #851 and see if he is happy with this and if we can get it merged in soon.

**Comment by tuupola** [comment]
Last commit in development branch 7 days ago does not look dead to me :)

**Comment by hakre** [comment]
@silentworks I'm perfectly OK with that. These PRs were just a stunt and actually I can not take the responsibility which it needs for proper care-taking to play these PRs. That's why I removed them. And that's all. I deleted those in my repos (from local repos I normally keep a backup, so really, feel free to contact me if there are any problems that stuck) and wrote that I'm out (if I were ever in). Github preserves those PRs. Feel free to use the code of my PRs unde the [`GPL-2.0+`](https://spdx.org/licenses/GPL-2.0+) license in case copyright applies.

For credits I'm okay with just something as simple as:

```
 hakre <https://hakre.wordpress.com/>
```

if wordpress.com goes down, then be it. you can google my nick anyway ;)

And I'm totally ok if that credit giving is with the source (e.g. just a `CREDITS` file at the very end if you don't want to put it in file (or if you prefer to put that into file, do it there, it's just I have no favor for this, just suit yourself(es))). The work anyway is getting anything into the code-base, so I don't want you to smaller your credits with all this, just in case someone asks for this and the deletion might look fishy. So please suit yourself(s).

_--signed_

**Comment by bensquire** [comment]
@tuupola Thanks for the code example, worked a treat
