### ISSUE TITLE
$app->error not handle errors in midleware call methods

### ISSUE THREAD

**Issue by EgorKluch** [slimphp/Slim#841]
```
use Slim\Slim;

$app = new Slim(array( 'debug' => false ));

$app->error(function ($e) use ($app) {
  $app->render('error.php');
});

class TestMiddleware extends \Slim\Middleware {
  public function call() {
    throw new \Exception('Middleware exception');
  }
}

class ErrorHandlerMiddleware extends \Slim\Middleware {
  public function call() {
    try {
      $this->next->call();
    }
    catch (\Exception $e) {
      Slim::getInstance()->error($e);
    }
  }
}

$app->add(new TestMiddleware());
# $app->add(new ErrorHandlerMiddleware());

$app->get('/', function () {
  throw new \Exception('Controller exception');
});

$app->run();
```

In this example Slim doesn't handle middleware exception. But handle controller exception.

If we uncomment "$app->add(new ErrorHandlerMiddleware());", we solved problem.
It's unpleasant crutch.

**Comment by danielgsims** [comment]
This happens because Slim doesn't create an exception handler like it does for errors. All exceptions in Slim are handled with try/catch blocks. If you wanted to handle this without a code change, you could write your own try/catch blocks that tunnel up to the Slim error method.

This could be satisfied most simply with a try/catch block around the first middleware call in the run method. A more elegant solution would be to create an exception handler that would be applicable to both middleware and exceptions within controllers. This would chiefly require a rewrite of the call method. There is some output buffering going on,t his would need to be refactored and applicable application-wide to handle exceptions globally.

**Comment by nevcos** [comment]
+1 for an exception handler applicable to both middleware and controllers

**Comment by codeguy** [comment]
This is resolved in the develop branch.
