### ISSUE TITLE
I can't use response object in notFound callback

### ISSUE THREAD

**Issue by DavidePastore** [slimphp/Slim#881]
Hi, I can't use 

``` php
$app->response()->setBody($myBody);
```

in my notFound callback. Is it normal?

Thanks

**Comment by StJudeWasHere** [comment]
You can use $app if you make it available in your callable, something like this would do the trick:

``` php`
$app->notFound(function() use ($app) { ... }
```

However, setting the body won't work in this case as notFound method calls the halt method, which resets the body to whatever is echoed in the callable. So instead of setting the body directly in the response you should just echo it.

``` php
echo $myBody
```

This doesn't seem to be an issue with the framework anyway, so you may want to post this in the [help forums](http://help.slimframework.com) to get better advice.

**Comment by DavidePastore** [comment]
@mnlg Hi, I think that this is an issue with the framework because if a developer makes a thing in a normal route, I think that he should make the same thing in a special route like the notFound one.

**Comment by silentworks** [comment]
@DavidePastore but notFound is not a route or even a special route.

**Comment by DavidePastore** [comment]
@silentworks Do you think it's impossibile to replicate the same environment in the notFound thing?

**Comment by tuupola** [comment]
Even in routes you usually do not call `setBody()`directly. You just `print` or `render()` your output. However I would also like Slim to implement more Sinatra like error handlers. Something like:

``` php
$app->error(403, function() use ($app) { 
    print "Access forbidden";
}

$app->error(404, function() use ($app) {
    $app->render("404.html");
}
```

**Comment by DavidePastore** [comment]
@tuupola I usually use `setBody()` when I create services that give me JSON. I don't know if it is a bad practice.

**Comment by tuupola** [comment]
I think it is matter of taste. However Slim documentation also suggests:

> Usually, you will never need to manually set the response body with the `setBody()` or `write()` methods; instead, the Slim app will do this for you. Whenever you `echo()` content inside a route’s callback function, the `echo()`’d content is captured in an output buffer and appended to the response body before the HTTP response is returned to the client.*

**Comment by codeguy** [comment]
Resolved in develop branch.
