### ISSUE TITLE
$_SERVER['SERVER_PORT'] isn't available in Google App Engine

### ISSUE THREAD

**Issue by german-chosen** [slimphp/Slim#962]
This the message I get:

Notice: Undefined index: SERVER_PORT in /base/data/home/apps/s~myapp/.../vendor/slim/slim/Slim/Environment.php on line 154

My solution was defining (in the beginning of the index.php file):

$_SERVER['SERVER_PORT'] = 80;

**Comment by diegoluisr** [comment]
I have this problem too, i hack que line
$env['SERVER_PORT'] = $_SERVER['SERVER_PORT'];
from slim/Environment.php
and i change this life for
$env['SERVER_PORT'] = isset($_SERVER['SERVER_PORT']) ? $_SERVER['SERVER_PORT'] : 80;

This Problem was reported in 2010, without Google solution.
https://code.google.com/p/googleappengine/issues/detail?id=2818

**Comment by codeguy** [comment]
Thanks. I'll add a default value of `80` if this value is not available. Do you want to submit a PR to the develop branch?

**Comment by tassoevan** [comment]
What about get the value from `$_SERVER["HTTP_HOST"]`? I don't know if it's a safe method to get this information (according to [the PHP docs](http://php.net/manual/en/reserved.variables.server.php), even `$_SERVER["SERVER_PORT"]` isn't), but does the trick.

**Comment by msjyoo** [comment]
Pull Request #1025 #1026 created that fixes this issue from both the master and develop branches.

**Comment by garnold** [comment]
@codeguy Reopening an oldie but goodie as I just bumped into this issue. App Engine supports HTTP and HTTPS, so defaulting to 80 doesn't always work. A more reliable way to set the default value is to consult `$_SERVER['HTTPS']`:

```php
if (!isset($_SERVER['SERVER_PORT'])) {
     $_SERVER['SERVER_PORT'] = $_SERVER['HTTPS'] == 'off' ? 80 : 443;
}
```
